/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.model.InlineResponse20010;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApoioApi
 */
@Ignore
public class ApoioApiTest {

    private final ApoioApi api = new ApoioApi();

    
    /**
     * Verifica a disponibilidade da API
     *
     * Serviço para verificar a disponibilidade da API.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void healthGetTest() throws ApiException {
        InlineResponse20010 response = api.healthGet();

        // TODO: test validations
    }
    
}
