/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.model.Boleto;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracao;
import br.com.fidias.sicoob_cobranca.model.BoletoBaixa;
import br.com.fidias.sicoob_cobranca.model.InlineResponse200;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2001;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2002;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2003;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2004;
import java.time.LocalDate;
import br.com.fidias.sicoob_cobranca.model.MensagensErro;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BoletoApi
 */
@Ignore
public class BoletoApiTest {

    private final BoletoApi api = new BoletoApi();

    
    /**
     * Consulta de dados de faixas de nosso número disponíveis.
     *
     * Serviço para consulta de dados de faixas de nosso número disponíveis.  Quando o campo validaDigitoVerificadorNossoNumero retornar o valor \&quot;0\&quot; a faixa \&quot;numeroInicial\&quot; e \&quot;numeroFinal\&quot; refere-se a numeração final (exemplo: 10 e 15 - utilização: 1-0 1-1 1-2 1-3 1-4 1-5). Mas se o campo validaDigitoVerificadorNossoNumero retornar o valor \&quot;1\&quot; a faixa \&quot;numeroInicial\&quot; e \&quot;numeroFinal\&quot; deverá ser calculado o DV (exemplo: 10 e 15 - utilização: 10-4 11-8 12-0 13-1 14-7 15-9).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosFaixasNossoNumeroGetTest() throws ApiException {
        Integer numeroCliente = null;
        Integer codigoModalidade = null;
        Integer quantidade = null;
        Long numeroContratoCobranca = null;
        InlineResponse2004 response = api.boletosFaixasNossoNumeroGet(numeroCliente, codigoModalidade, quantidade, numeroContratoCobranca);

        // TODO: test validations
    }
    
    /**
     * Consultar boleto
     *
     * Serviço para consulta de um boleto bancário. Utiliza as informações do beneficiário logado (número da cooperativa, número identificador do beneficiário e conta corrente), juntamente com a informação do identificador do boleto (nosso número), ou da linha digitável ou do código de barras.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosGetTest() throws ApiException {
        Integer numeroCliente = null;
        Integer codigoModalidade = null;
        Integer nossoNumero = null;
        String linhaDigitavel = null;
        String codigoBarras = null;
        Integer numeroContratoCobranca = null;
        InlineResponse200 response = api.boletosGet(numeroCliente, codigoModalidade, nossoNumero, linhaDigitavel, codigoBarras, numeroContratoCobranca);

        // TODO: test validations
    }
    
    /**
     * Comandar a baixa de boletos
     *
     * Serviço para comandar a baixa de boletos informados.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosNossoNumeroBaixarPostTest() throws ApiException {
        Integer nossoNumero = null;
        BoletoBaixa boleto = null;
        api.boletosNossoNumeroBaixarPost(nossoNumero, boleto);

        // TODO: test validations
    }
    
    /**
     * Alterar dados de um boleto
     *
     * Serviço para alteração de dados de boleto já registrado.  Deve ser feita a alteração de somente um objeto do boleto por requisição. **Objetos de alteração do boleto:** - seuNumero - desconto - abatimento - multa - jurosMora - rateioCredito - pix - prorrogacaoVencimento - prorrogacaoLimitePagamento
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosNossoNumeroPatchTest() throws ApiException {
        Integer nossoNumero = null;
        BoletoAlteracao boleto = null;
        api.boletosNossoNumeroPatch(nossoNumero, boleto);

        // TODO: test validations
    }
    
    /**
     * Incluir boletos
     *
     * Serviço para a inclusão de boletos. É possível a inclusão de 1 boleto por requisição.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosPostTest() throws ApiException {
        Boleto boleto = null;
        InlineResponse2001 response = api.boletosPost(boleto);

        // TODO: test validations
    }
    
    /**
     * Emitir segunda via de um boleto
     *
     * Serviço para emissão da segunda via de boleto já registrado. Utiliza as informações do beneficiário logado (número da cooperativa, número identificador do beneficiário e conta corrente), juntamente com a informação do identificador do boleto (nosso número), ou da linha digitável ou do código de barras. Quando informados código de barras ou linha digitável, a pesquisa é realiazada prioritariamente por estes parâmetros.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosSegundaViaGetTest() throws ApiException {
        Integer numeroCliente = null;
        Integer codigoModalidade = null;
        Integer nossoNumero = null;
        String linhaDigitavel = null;
        String codigoBarras = null;
        Boolean gerarPdf = null;
        Long numeroContratoCobranca = null;
        InlineResponse2003 response = api.boletosSegundaViaGet(numeroCliente, codigoModalidade, nossoNumero, linhaDigitavel, codigoBarras, gerarPdf, numeroContratoCobranca);

        // TODO: test validations
    }
    
    /**
     * Listar Boletos por Pagador
     *
     * Serviço para listagem de boletos por Pagador.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pagadoresNumeroCpfCnpjBoletosGetTest() throws ApiException {
        String numeroCpfCnpj = null;
        Integer numeroCliente = null;
        Integer codigoSituacao = null;
        LocalDate dataInicio = null;
        LocalDate dataFim = null;
        InlineResponse2002 response = api.pagadoresNumeroCpfCnpjBoletosGet(numeroCpfCnpj, numeroCliente, codigoSituacao, dataInicio, dataFim);

        // TODO: test validations
    }
    
}
