/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.model.InlineObject;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2005;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2006;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2007;
import br.com.fidias.sicoob_cobranca.model.MensagensErro;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MovimentaoApi
 */
@Ignore
public class MovimentaoApiTest {

    private final MovimentaoApi api = new MovimentaoApi();

    
    /**
     * Download do(s) arquivo(s) de movimentação.
     *
     * Serviço para obter um arquivo de movimentação.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosMovimentacoesDownloadGetTest() throws ApiException {
        Integer numeroCliente = null;
        Integer codigoSolicitacao = null;
        Integer idArquivo = null;
        InlineResponse2007 response = api.boletosMovimentacoesDownloadGet(numeroCliente, codigoSolicitacao, idArquivo);

        // TODO: test validations
    }
    
    /**
     * Consultar a situação da solicitação da movimentação
     *
     * Serviço para consultar a situação da solicitação da movimentação.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosMovimentacoesGetTest() throws ApiException {
        Integer numeroCliente = null;
        Integer codigoSolicitacao = null;
        InlineResponse2005 response = api.boletosMovimentacoesGet(numeroCliente, codigoSolicitacao);

        // TODO: test validations
    }
    
    /**
     * Solicitar a movimentação da carteira de cobrança registrada para beneficiário informado
     *
     * Serviço para solicitar a movimentação da carteira de cobrança registrada para beneficiário informado. Os movimentos disponíveis para solicitaçao são 1. Entrada 2. Prorrogação 3. A Vencer 4. Vencido 5. Liquidação 6. Baixa 7. Vinculado Operações Crédito * As consultas estão limitadas em um período máximo de 2 dias.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosMovimentacoesPostTest() throws ApiException {
        InlineObject solicitacao = null;
        InlineResponse2006 response = api.boletosMovimentacoesPost(solicitacao);

        // TODO: test validations
    }
    
}
