/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.model.MensagensErro;
import br.com.fidias.sicoob_cobranca.model.Negativacao;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NegativaoApi
 */
@Ignore
public class NegativaoApiTest {

    private final NegativaoApi api = new NegativaoApi();

    
    /**
     * Baixar a negativação de pagadores de boletos
     *
     * Serviço para comandar uma baixa da negativação de pagadores de boletos informados. Será enviado um pedido de baixa para o serviço de proteção ao crédito.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosNossoNumeroNegativacoesDeleteTest() throws ApiException {
        Integer nossoNumero = null;
        Negativacao boleto = null;
        api.boletosNossoNumeroNegativacoesDelete(nossoNumero, boleto);

        // TODO: test validations
    }
    
    /**
     * Cancelar o apontamento da negativação de pagadores de boletos
     *
     * Serviço para cancelar o apontamento da negativação de pagadores de boletos informados. O boleto não será enviado ao serviço de proteção ao crédito.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosNossoNumeroNegativacoesPatchTest() throws ApiException {
        Integer nossoNumero = null;
        Negativacao boleto = null;
        api.boletosNossoNumeroNegativacoesPatch(nossoNumero, boleto);

        // TODO: test validations
    }
    
    /**
     * Negativar pagadores de boletos
     *
     * Serviço para indicar a negativação de pagadores de boletos informados. A negativação é o registro de pendências ou restrições nos órgãos de proteção ao crédito. No Sicoob, o parceiro para este serviço é o SERASA.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boletosNossoNumeroNegativacoesPostTest() throws ApiException {
        Integer nossoNumero = null;
        Negativacao boletos = null;
        api.boletosNossoNumeroNegativacoesPost(nossoNumero, boletos);

        // TODO: test validations
    }
    
}
