/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2008;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2009;
import br.com.fidias.sicoob_cobranca.model.InlineResponse201;
import java.time.LocalDate;
import br.com.fidias.sicoob_cobranca.model.MensagensErro;
import br.com.fidias.sicoob_cobranca.model.WebhookAlteracao;
import br.com.fidias.sicoob_cobranca.model.WebhookCadastro;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookApi
 */
@Ignore
public class WebhookApiTest {

    private final WebhookApi api = new WebhookApi();

    
    /**
     * Consultar os webhooks cadastrados.
     *
     * Serviço para consultar os detalhes dos webhooks cadastrados.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksGetTest() throws ApiException {
        Long idWebhook = null;
        Integer codigoTipoMovimento = null;
        InlineResponse2008 response = api.webhooksGet(idWebhook, codigoTipoMovimento);

        // TODO: test validations
    }
    
    /**
     * Excluir um webhook.
     *
     * Serviço responsável por remover permanentemente um webhook registrado, encerrando o envio de notificações para a URL vinculada.\&quot; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksIdWebhookDeleteTest() throws ApiException {
        Long idWebhook = null;
        api.webhooksIdWebhookDelete(idWebhook);

        // TODO: test validations
    }
    
    /**
     * Atualizar um webhook cadastrado.
     *
     * Serviço de atualização de webhook. Ao modificar a URL, a situação do webhook será automaticamente alterada para &#39;1 - Aguardando validação&#39; e permanecerá assim até que a nova URL seja validada com sucesso. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksIdWebhookPatchTest() throws ApiException {
        Long idWebhook = null;
        WebhookAlteracao webhook = null;
        api.webhooksIdWebhookPatch(idWebhook, webhook);

        // TODO: test validations
    }
    
    /**
     * Reativar um webhook inativo.
     *
     * Serviço de reativação de webhook desativado, restabelecendo o recebimento de notificações. A situação do webhook será atualizada para &#39;1 - Aguardando validação&#39; e permanecerá assim até que a URL seja validada com sucesso. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksIdWebhookReativarPatchTest() throws ApiException {
        Long idWebhook = null;
        api.webhooksIdWebhookReativarPatch(idWebhook);

        // TODO: test validations
    }
    
    /**
     * Consultar solicitações de um webhook.
     *
     * Consulta as solicitações de notificação para um webhook com base na data de solicitação informada.  Retorna o histórico das tentativas de notificação, incluindo o status e a resposta da requisição. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksIdWebhookSolicitacoesGetTest() throws ApiException {
        Long idWebhook = null;
        LocalDate dataSolicitacao = null;
        Integer pagina = null;
        Integer codigoSolicitacaoSituacao = null;
        String codigoBarras = null;
        Long nossoNumero = null;
        InlineResponse2009 response = api.webhooksIdWebhookSolicitacoesGet(idWebhook, dataSolicitacao, pagina, codigoSolicitacaoSituacao, codigoBarras, nossoNumero);

        // TODO: test validations
    }
    
    /**
     * Cadastrar um webhook para receber notificações de acordo com o tipo de movimento.
     *
     * Este serviço permite cadastrar uma URL que será notificada sempre que ocorrer um evento associado a um tipo de movimento. O webhook pode ser configurado para o período de movimentação atual (D0). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhooksPostTest() throws ApiException {
        WebhookCadastro webhook = null;
        InlineResponse201 response = api.webhooksPost(webhook);

        // TODO: test validations
    }
    
}
