/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoAbatimento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoDesconto;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoEspecieDocumento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoJurosMora;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoMulta;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoPix;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoProrrogacaoLimitePagamento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoProrrogacaoVencimento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoRateioCredito;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoSeuNumero;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoValorNominal;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BoletoAlteracao
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:07:18.842-03:00[America/Fortaleza]")
public class BoletoAlteracao {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Long numeroCliente;

  public static final String SERIALIZED_NAME_CODIGO_MODALIDADE = "codigoModalidade";
  @SerializedName(SERIALIZED_NAME_CODIGO_MODALIDADE)
  private Integer codigoModalidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  private Long numeroContratoCobranca;

  public static final String SERIALIZED_NAME_ESPECIE_DOCUMENTO = "especieDocumento";
  @SerializedName(SERIALIZED_NAME_ESPECIE_DOCUMENTO)
  private BoletoAlteracaoEspecieDocumento especieDocumento;

  public static final String SERIALIZED_NAME_SEU_NUMERO = "seuNumero";
  @SerializedName(SERIALIZED_NAME_SEU_NUMERO)
  private BoletoAlteracaoSeuNumero seuNumero;

  public static final String SERIALIZED_NAME_DESCONTO = "desconto";
  @SerializedName(SERIALIZED_NAME_DESCONTO)
  private BoletoAlteracaoDesconto desconto;

  public static final String SERIALIZED_NAME_ABATIMENTO = "abatimento";
  @SerializedName(SERIALIZED_NAME_ABATIMENTO)
  private BoletoAlteracaoAbatimento abatimento;

  public static final String SERIALIZED_NAME_MULTA = "multa";
  @SerializedName(SERIALIZED_NAME_MULTA)
  private BoletoAlteracaoMulta multa;

  public static final String SERIALIZED_NAME_JUROS_MORA = "jurosMora";
  @SerializedName(SERIALIZED_NAME_JUROS_MORA)
  private BoletoAlteracaoJurosMora jurosMora;

  public static final String SERIALIZED_NAME_RATEIO_CREDITO = "rateioCredito";
  @SerializedName(SERIALIZED_NAME_RATEIO_CREDITO)
  private BoletoAlteracaoRateioCredito rateioCredito;

  public static final String SERIALIZED_NAME_PIX = "pix";
  @SerializedName(SERIALIZED_NAME_PIX)
  private BoletoAlteracaoPix pix;

  public static final String SERIALIZED_NAME_PRORROGACAO_VENCIMENTO = "prorrogacaoVencimento";
  @SerializedName(SERIALIZED_NAME_PRORROGACAO_VENCIMENTO)
  private BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento;

  public static final String SERIALIZED_NAME_PRORROGACAO_LIMITE_PAGAMENTO = "prorrogacaoLimitePagamento";
  @SerializedName(SERIALIZED_NAME_PRORROGACAO_LIMITE_PAGAMENTO)
  private BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento;

  public static final String SERIALIZED_NAME_VALOR_NOMINAL = "valorNominal";
  @SerializedName(SERIALIZED_NAME_VALOR_NOMINAL)
  private BoletoAlteracaoValorNominal valorNominal;


  public BoletoAlteracao numeroCliente(Long numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário no Sisbr.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "25546454", required = true, value = "Número que identifica o contrato do beneficiário no Sisbr.")

  public Long getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Long numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public BoletoAlteracao codigoModalidade(Integer codigoModalidade) {
    
    this.codigoModalidade = codigoModalidade;
    return this;
  }

   /**
   * Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 3 - CAUCIONADA - 4 - VINCULADA - 5 - CARNÊ DE PAGAMENTOS - 8 - COBRANÇA CONTA CAPITAL
   * @return codigoModalidade
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 3 - CAUCIONADA - 4 - VINCULADA - 5 - CARNÊ DE PAGAMENTOS - 8 - COBRANÇA CONTA CAPITAL")

  public Integer getCodigoModalidade() {
    return codigoModalidade;
  }


  public void setCodigoModalidade(Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }


  public BoletoAlteracao numeroContratoCobranca(Long numeroContratoCobranca) {
    
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Indicar o id do contatroCobranca
   * @return numeroContratoCobranca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Indicar o id do contatroCobranca")

  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }


  public void setNumeroContratoCobranca(Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  public BoletoAlteracao especieDocumento(BoletoAlteracaoEspecieDocumento especieDocumento) {
    
    this.especieDocumento = especieDocumento;
    return this;
  }

   /**
   * Get especieDocumento
   * @return especieDocumento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoEspecieDocumento getEspecieDocumento() {
    return especieDocumento;
  }


  public void setEspecieDocumento(BoletoAlteracaoEspecieDocumento especieDocumento) {
    this.especieDocumento = especieDocumento;
  }


  public BoletoAlteracao seuNumero(BoletoAlteracaoSeuNumero seuNumero) {
    
    this.seuNumero = seuNumero;
    return this;
  }

   /**
   * Get seuNumero
   * @return seuNumero
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoSeuNumero getSeuNumero() {
    return seuNumero;
  }


  public void setSeuNumero(BoletoAlteracaoSeuNumero seuNumero) {
    this.seuNumero = seuNumero;
  }


  public BoletoAlteracao desconto(BoletoAlteracaoDesconto desconto) {
    
    this.desconto = desconto;
    return this;
  }

   /**
   * Get desconto
   * @return desconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoDesconto getDesconto() {
    return desconto;
  }


  public void setDesconto(BoletoAlteracaoDesconto desconto) {
    this.desconto = desconto;
  }


  public BoletoAlteracao abatimento(BoletoAlteracaoAbatimento abatimento) {
    
    this.abatimento = abatimento;
    return this;
  }

   /**
   * Get abatimento
   * @return abatimento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoAbatimento getAbatimento() {
    return abatimento;
  }


  public void setAbatimento(BoletoAlteracaoAbatimento abatimento) {
    this.abatimento = abatimento;
  }


  public BoletoAlteracao multa(BoletoAlteracaoMulta multa) {
    
    this.multa = multa;
    return this;
  }

   /**
   * Get multa
   * @return multa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoMulta getMulta() {
    return multa;
  }


  public void setMulta(BoletoAlteracaoMulta multa) {
    this.multa = multa;
  }


  public BoletoAlteracao jurosMora(BoletoAlteracaoJurosMora jurosMora) {
    
    this.jurosMora = jurosMora;
    return this;
  }

   /**
   * Get jurosMora
   * @return jurosMora
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoJurosMora getJurosMora() {
    return jurosMora;
  }


  public void setJurosMora(BoletoAlteracaoJurosMora jurosMora) {
    this.jurosMora = jurosMora;
  }


  public BoletoAlteracao rateioCredito(BoletoAlteracaoRateioCredito rateioCredito) {
    
    this.rateioCredito = rateioCredito;
    return this;
  }

   /**
   * Get rateioCredito
   * @return rateioCredito
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoRateioCredito getRateioCredito() {
    return rateioCredito;
  }


  public void setRateioCredito(BoletoAlteracaoRateioCredito rateioCredito) {
    this.rateioCredito = rateioCredito;
  }


  public BoletoAlteracao pix(BoletoAlteracaoPix pix) {
    
    this.pix = pix;
    return this;
  }

   /**
   * Get pix
   * @return pix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoPix getPix() {
    return pix;
  }


  public void setPix(BoletoAlteracaoPix pix) {
    this.pix = pix;
  }


  public BoletoAlteracao prorrogacaoVencimento(BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento) {
    
    this.prorrogacaoVencimento = prorrogacaoVencimento;
    return this;
  }

   /**
   * Get prorrogacaoVencimento
   * @return prorrogacaoVencimento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoProrrogacaoVencimento getProrrogacaoVencimento() {
    return prorrogacaoVencimento;
  }


  public void setProrrogacaoVencimento(BoletoAlteracaoProrrogacaoVencimento prorrogacaoVencimento) {
    this.prorrogacaoVencimento = prorrogacaoVencimento;
  }


  public BoletoAlteracao prorrogacaoLimitePagamento(BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento) {
    
    this.prorrogacaoLimitePagamento = prorrogacaoLimitePagamento;
    return this;
  }

   /**
   * Get prorrogacaoLimitePagamento
   * @return prorrogacaoLimitePagamento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoProrrogacaoLimitePagamento getProrrogacaoLimitePagamento() {
    return prorrogacaoLimitePagamento;
  }


  public void setProrrogacaoLimitePagamento(BoletoAlteracaoProrrogacaoLimitePagamento prorrogacaoLimitePagamento) {
    this.prorrogacaoLimitePagamento = prorrogacaoLimitePagamento;
  }


  public BoletoAlteracao valorNominal(BoletoAlteracaoValorNominal valorNominal) {
    
    this.valorNominal = valorNominal;
    return this;
  }

   /**
   * Get valorNominal
   * @return valorNominal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BoletoAlteracaoValorNominal getValorNominal() {
    return valorNominal;
  }


  public void setValorNominal(BoletoAlteracaoValorNominal valorNominal) {
    this.valorNominal = valorNominal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracao boletoAlteracao = (BoletoAlteracao) o;
    return Objects.equals(this.numeroCliente, boletoAlteracao.numeroCliente) &&
        Objects.equals(this.codigoModalidade, boletoAlteracao.codigoModalidade) &&
        Objects.equals(this.numeroContratoCobranca, boletoAlteracao.numeroContratoCobranca) &&
        Objects.equals(this.especieDocumento, boletoAlteracao.especieDocumento) &&
        Objects.equals(this.seuNumero, boletoAlteracao.seuNumero) &&
        Objects.equals(this.desconto, boletoAlteracao.desconto) &&
        Objects.equals(this.abatimento, boletoAlteracao.abatimento) &&
        Objects.equals(this.multa, boletoAlteracao.multa) &&
        Objects.equals(this.jurosMora, boletoAlteracao.jurosMora) &&
        Objects.equals(this.rateioCredito, boletoAlteracao.rateioCredito) &&
        Objects.equals(this.pix, boletoAlteracao.pix) &&
        Objects.equals(this.prorrogacaoVencimento, boletoAlteracao.prorrogacaoVencimento) &&
        Objects.equals(this.prorrogacaoLimitePagamento, boletoAlteracao.prorrogacaoLimitePagamento) &&
        Objects.equals(this.valorNominal, boletoAlteracao.valorNominal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, codigoModalidade, numeroContratoCobranca, especieDocumento, seuNumero, desconto, abatimento, multa, jurosMora, rateioCredito, pix, prorrogacaoVencimento, prorrogacaoLimitePagamento, valorNominal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracao {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    codigoModalidade: ").append(toIndentedString(codigoModalidade)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("    especieDocumento: ").append(toIndentedString(especieDocumento)).append("\n");
    sb.append("    seuNumero: ").append(toIndentedString(seuNumero)).append("\n");
    sb.append("    desconto: ").append(toIndentedString(desconto)).append("\n");
    sb.append("    abatimento: ").append(toIndentedString(abatimento)).append("\n");
    sb.append("    multa: ").append(toIndentedString(multa)).append("\n");
    sb.append("    jurosMora: ").append(toIndentedString(jurosMora)).append("\n");
    sb.append("    rateioCredito: ").append(toIndentedString(rateioCredito)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("    prorrogacaoVencimento: ").append(toIndentedString(prorrogacaoVencimento)).append("\n");
    sb.append("    prorrogacaoLimitePagamento: ").append(toIndentedString(prorrogacaoLimitePagamento)).append("\n");
    sb.append("    valorNominal: ").append(toIndentedString(valorNominal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

