/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BoletoAlteracaoSeuNumero
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class BoletoAlteracaoSeuNumero {
  public static final String SERIALIZED_NAME_SEU_NUMERO = "seuNumero";
  @SerializedName(SERIALIZED_NAME_SEU_NUMERO)
  private String seuNumero;

  public static final String SERIALIZED_NAME_IDENTIFICACAO_BOLETO_EMPRESA = "identificacaoBoletoEmpresa";
  @SerializedName(SERIALIZED_NAME_IDENTIFICACAO_BOLETO_EMPRESA)
  private String identificacaoBoletoEmpresa;


  public BoletoAlteracaoSeuNumero seuNumero(String seuNumero) {
    
    this.seuNumero = seuNumero;
    return this;
  }

   /**
   * Número do boleto no sistema do beneficiário. &#x60;Tamanho máximo 18&#x60;
   * @return seuNumero
  **/
  @ApiModelProperty(example = "209", required = true, value = "Número do boleto no sistema do beneficiário. `Tamanho máximo 18`")

  public String getSeuNumero() {
    return seuNumero;
  }


  public void setSeuNumero(String seuNumero) {
    this.seuNumero = seuNumero;
  }


  public BoletoAlteracaoSeuNumero identificacaoBoletoEmpresa(String identificacaoBoletoEmpresa) {
    
    this.identificacaoBoletoEmpresa = identificacaoBoletoEmpresa;
    return this;
  }

   /**
   * Número de controle do boleto determinado pelo beneficiário.
   * @return identificacaoBoletoEmpresa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "209", value = "Número de controle do boleto determinado pelo beneficiário.")

  public String getIdentificacaoBoletoEmpresa() {
    return identificacaoBoletoEmpresa;
  }


  public void setIdentificacaoBoletoEmpresa(String identificacaoBoletoEmpresa) {
    this.identificacaoBoletoEmpresa = identificacaoBoletoEmpresa;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracaoSeuNumero boletoAlteracaoSeuNumero = (BoletoAlteracaoSeuNumero) o;
    return Objects.equals(this.seuNumero, boletoAlteracaoSeuNumero.seuNumero) &&
        Objects.equals(this.identificacaoBoletoEmpresa, boletoAlteracaoSeuNumero.identificacaoBoletoEmpresa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seuNumero, identificacaoBoletoEmpresa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracaoSeuNumero {\n");
    sb.append("    seuNumero: ").append(toIndentedString(seuNumero)).append("\n");
    sb.append("    identificacaoBoletoEmpresa: ").append(toIndentedString(identificacaoBoletoEmpresa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

