/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * BoletoAlteracaoProrrogacaoLimitePagamento
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:07:18.842-03:00[America/Fortaleza]")
public class BoletoAlteracaoProrrogacaoLimitePagamento {
  public static final String SERIALIZED_NAME_DATA_LIMITE_PAGAMENTO = "dataLimitePagamento";
  @SerializedName(SERIALIZED_NAME_DATA_LIMITE_PAGAMENTO)
  private LocalDate dataLimitePagamento;


  public BoletoAlteracaoProrrogacaoLimitePagamento dataLimitePagamento(LocalDate dataLimitePagamento) {
    
    this.dataLimitePagamento = dataLimitePagamento;
    return this;
  }

   /**
   * Nova data limite para pagamento do boleto.
   * @return dataLimitePagamento
  **/
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", required = true, value = "Nova data limite para pagamento do boleto.")

  public LocalDate getDataLimitePagamento() {
    return dataLimitePagamento;
  }


  public void setDataLimitePagamento(LocalDate dataLimitePagamento) {
    this.dataLimitePagamento = dataLimitePagamento;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracaoProrrogacaoLimitePagamento boletoAlteracaoProrrogacaoLimitePagamento = (BoletoAlteracaoProrrogacaoLimitePagamento) o;
    return Objects.equals(this.dataLimitePagamento, boletoAlteracaoProrrogacaoLimitePagamento.dataLimitePagamento);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataLimitePagamento);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracaoProrrogacaoLimitePagamento {\n");
    sb.append("    dataLimitePagamento: ").append(toIndentedString(dataLimitePagamento)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

