/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BoletoBaixa
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class BoletoBaixa {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_CODIGO_MODALIDADE = "codigoModalidade";
  @SerializedName(SERIALIZED_NAME_CODIGO_MODALIDADE)
  private Integer codigoModalidade;


  public BoletoBaixa numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "5224", required = true, value = "Número que identifica o contrato do beneficiário.")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public BoletoBaixa codigoModalidade(Integer codigoModalidade) {
    
    this.codigoModalidade = codigoModalidade;
    return this;
  }

   /**
   * Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 3 - CAUCIONADA - 4 - VINCULADA - 5 - CARNÊ DE PAGAMENTOS - 8 - COBRANÇA CONTA CAPITAL
   * @return codigoModalidade
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 3 - CAUCIONADA - 4 - VINCULADA - 5 - CARNÊ DE PAGAMENTOS - 8 - COBRANÇA CONTA CAPITAL")

  public Integer getCodigoModalidade() {
    return codigoModalidade;
  }


  public void setCodigoModalidade(Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoBaixa boletoBaixa = (BoletoBaixa) o;
    return Objects.equals(this.numeroCliente, boletoBaixa.numeroCliente) &&
        Objects.equals(this.codigoModalidade, boletoBaixa.codigoModalidade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, codigoModalidade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoBaixa {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    codigoModalidade: ").append(toIndentedString(codigoModalidade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

