/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.RateioCredito;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BoletoAlteracaoRateioCredito
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class BoletoAlteracaoRateioCredito {
  public static final String SERIALIZED_NAME_TIPO_OPERACAO = "tipoOperacao";
  @SerializedName(SERIALIZED_NAME_TIPO_OPERACAO)
  private Integer tipoOperacao;

  public static final String SERIALIZED_NAME_RATEIO_CREDITOS = "rateioCreditos";
  @SerializedName(SERIALIZED_NAME_RATEIO_CREDITOS)
  private List<RateioCredito> rateioCreditos = new ArrayList<>();


  public BoletoAlteracaoRateioCredito tipoOperacao(Integer tipoOperacao) {
    
    this.tipoOperacao = tipoOperacao;
    return this;
  }

   /**
   * Identificador da Operação de Rateio de Crédito   - 2 Alterar o Rateio de Crédito feito na Inclusão do Boleto   - 3 Excluir o Rateio de Crédito.
   * @return tipoOperacao
  **/
  @ApiModelProperty(example = "2", required = true, value = "Identificador da Operação de Rateio de Crédito   - 2 Alterar o Rateio de Crédito feito na Inclusão do Boleto   - 3 Excluir o Rateio de Crédito.")

  public Integer getTipoOperacao() {
    return tipoOperacao;
  }


  public void setTipoOperacao(Integer tipoOperacao) {
    this.tipoOperacao = tipoOperacao;
  }


  public BoletoAlteracaoRateioCredito rateioCreditos(List<RateioCredito> rateioCreditos) {
    
    this.rateioCreditos = rateioCreditos;
    return this;
  }

  public BoletoAlteracaoRateioCredito addRateioCreditosItem(RateioCredito rateioCreditosItem) {
    this.rateioCreditos.add(rateioCreditosItem);
    return this;
  }

   /**
   * Get rateioCreditos
   * @return rateioCreditos
  **/
  @ApiModelProperty(required = true, value = "")

  public List<RateioCredito> getRateioCreditos() {
    return rateioCreditos;
  }


  public void setRateioCreditos(List<RateioCredito> rateioCreditos) {
    this.rateioCreditos = rateioCreditos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracaoRateioCredito boletoAlteracaoRateioCredito = (BoletoAlteracaoRateioCredito) o;
    return Objects.equals(this.tipoOperacao, boletoAlteracaoRateioCredito.tipoOperacao) &&
        Objects.equals(this.rateioCreditos, boletoAlteracaoRateioCredito.rateioCreditos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoOperacao, rateioCreditos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracaoRateioCredito {\n");
    sb.append("    tipoOperacao: ").append(toIndentedString(tipoOperacao)).append("\n");
    sb.append("    rateioCreditos: ").append(toIndentedString(rateioCreditos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

