/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * BoletoAlteracaoDesconto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:07:18.842-03:00[America/Fortaleza]")
public class BoletoAlteracaoDesconto {
  public static final String SERIALIZED_NAME_TIPO_DESCONTO = "tipoDesconto";
  @SerializedName(SERIALIZED_NAME_TIPO_DESCONTO)
  private Long tipoDesconto;

  public static final String SERIALIZED_NAME_DATA_PRIMEIRO_DESCONTO = "dataPrimeiroDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_PRIMEIRO_DESCONTO)
  private LocalDate dataPrimeiroDesconto;

  public static final String SERIALIZED_NAME_VALOR_PRIMEIRO_DESCONTO = "valorPrimeiroDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_PRIMEIRO_DESCONTO)
  private Double valorPrimeiroDesconto;

  public static final String SERIALIZED_NAME_DATA_SEGUNDO_DESCONTO = "dataSegundoDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_SEGUNDO_DESCONTO)
  private LocalDate dataSegundoDesconto;

  public static final String SERIALIZED_NAME_VALOR_SEGUNDO_DESCONTO = "valorSegundoDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_SEGUNDO_DESCONTO)
  private Double valorSegundoDesconto;

  public static final String SERIALIZED_NAME_DATA_TERCEIRO_DESCONTO = "dataTerceiroDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_TERCEIRO_DESCONTO)
  private LocalDate dataTerceiroDesconto;

  public static final String SERIALIZED_NAME_VALOR_TERCEIRO_DESCONTO = "valorTerceiroDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_TERCEIRO_DESCONTO)
  private Double valorTerceiroDesconto;


  public BoletoAlteracaoDesconto tipoDesconto(Long tipoDesconto) {
    
    this.tipoDesconto = tipoDesconto;
    return this;
  }

   /**
   * Informar o tipo de desconto atribuido ao boleto.   - 0 Sem Desconto   - 1 Valor Fixo Até a Data Informada   - 2 Percentual até a data informada   - 3 Valor por antecipação dia corrido   - 4 Valor por antecipação dia útil   - 5 Percentual por antecipação dia corrido   - 6 Percentual por antecipação dia útil
   * @return tipoDesconto
  **/
  @ApiModelProperty(example = "1", required = true, value = "Informar o tipo de desconto atribuido ao boleto.   - 0 Sem Desconto   - 1 Valor Fixo Até a Data Informada   - 2 Percentual até a data informada   - 3 Valor por antecipação dia corrido   - 4 Valor por antecipação dia útil   - 5 Percentual por antecipação dia corrido   - 6 Percentual por antecipação dia útil")

  public Long getTipoDesconto() {
    return tipoDesconto;
  }


  public void setTipoDesconto(Long tipoDesconto) {
    this.tipoDesconto = tipoDesconto;
  }


  public BoletoAlteracaoDesconto dataPrimeiroDesconto(LocalDate dataPrimeiroDesconto) {
    
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
    return this;
  }

   /**
   * Data do primeiro desconto.
   * @return dataPrimeiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", value = "Data do primeiro desconto.")

  public LocalDate getDataPrimeiroDesconto() {
    return dataPrimeiroDesconto;
  }


  public void setDataPrimeiroDesconto(LocalDate dataPrimeiroDesconto) {
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
  }


  public BoletoAlteracaoDesconto valorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
    return this;
  }

   /**
   * Valor do primeiro desconto.
   * @return valorPrimeiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1.0", value = "Valor do primeiro desconto.")

  public Double getValorPrimeiroDesconto() {
    return valorPrimeiroDesconto;
  }


  public void setValorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
  }


  public BoletoAlteracaoDesconto dataSegundoDesconto(LocalDate dataSegundoDesconto) {
    
    this.dataSegundoDesconto = dataSegundoDesconto;
    return this;
  }

   /**
   * Data do segundo desconto.
   * @return dataSegundoDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", value = "Data do segundo desconto.")

  public LocalDate getDataSegundoDesconto() {
    return dataSegundoDesconto;
  }


  public void setDataSegundoDesconto(LocalDate dataSegundoDesconto) {
    this.dataSegundoDesconto = dataSegundoDesconto;
  }


  public BoletoAlteracaoDesconto valorSegundoDesconto(Double valorSegundoDesconto) {
    
    this.valorSegundoDesconto = valorSegundoDesconto;
    return this;
  }

   /**
   * Valor do segundo desconto.
   * @return valorSegundoDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.0", value = "Valor do segundo desconto.")

  public Double getValorSegundoDesconto() {
    return valorSegundoDesconto;
  }


  public void setValorSegundoDesconto(Double valorSegundoDesconto) {
    this.valorSegundoDesconto = valorSegundoDesconto;
  }


  public BoletoAlteracaoDesconto dataTerceiroDesconto(LocalDate dataTerceiroDesconto) {
    
    this.dataTerceiroDesconto = dataTerceiroDesconto;
    return this;
  }

   /**
   * Data do terceiro desconto.
   * @return dataTerceiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", value = "Data do terceiro desconto.")

  public LocalDate getDataTerceiroDesconto() {
    return dataTerceiroDesconto;
  }


  public void setDataTerceiroDesconto(LocalDate dataTerceiroDesconto) {
    this.dataTerceiroDesconto = dataTerceiroDesconto;
  }


  public BoletoAlteracaoDesconto valorTerceiroDesconto(Double valorTerceiroDesconto) {
    
    this.valorTerceiroDesconto = valorTerceiroDesconto;
    return this;
  }

   /**
   * Valor do terceiro desconto.
   * @return valorTerceiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0.0", value = "Valor do terceiro desconto.")

  public Double getValorTerceiroDesconto() {
    return valorTerceiroDesconto;
  }


  public void setValorTerceiroDesconto(Double valorTerceiroDesconto) {
    this.valorTerceiroDesconto = valorTerceiroDesconto;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoletoAlteracaoDesconto boletoAlteracaoDesconto = (BoletoAlteracaoDesconto) o;
    return Objects.equals(this.tipoDesconto, boletoAlteracaoDesconto.tipoDesconto) &&
        Objects.equals(this.dataPrimeiroDesconto, boletoAlteracaoDesconto.dataPrimeiroDesconto) &&
        Objects.equals(this.valorPrimeiroDesconto, boletoAlteracaoDesconto.valorPrimeiroDesconto) &&
        Objects.equals(this.dataSegundoDesconto, boletoAlteracaoDesconto.dataSegundoDesconto) &&
        Objects.equals(this.valorSegundoDesconto, boletoAlteracaoDesconto.valorSegundoDesconto) &&
        Objects.equals(this.dataTerceiroDesconto, boletoAlteracaoDesconto.dataTerceiroDesconto) &&
        Objects.equals(this.valorTerceiroDesconto, boletoAlteracaoDesconto.valorTerceiroDesconto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipoDesconto, dataPrimeiroDesconto, valorPrimeiroDesconto, dataSegundoDesconto, valorSegundoDesconto, dataTerceiroDesconto, valorTerceiroDesconto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoletoAlteracaoDesconto {\n");
    sb.append("    tipoDesconto: ").append(toIndentedString(tipoDesconto)).append("\n");
    sb.append("    dataPrimeiroDesconto: ").append(toIndentedString(dataPrimeiroDesconto)).append("\n");
    sb.append("    valorPrimeiroDesconto: ").append(toIndentedString(valorPrimeiroDesconto)).append("\n");
    sb.append("    dataSegundoDesconto: ").append(toIndentedString(dataSegundoDesconto)).append("\n");
    sb.append("    valorSegundoDesconto: ").append(toIndentedString(valorSegundoDesconto)).append("\n");
    sb.append("    dataTerceiroDesconto: ").append(toIndentedString(dataTerceiroDesconto)).append("\n");
    sb.append("    valorTerceiroDesconto: ").append(toIndentedString(valorTerceiroDesconto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

