/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.BoletoPagador;
import br.com.fidias.sicoob_cobranca.model.InlineResponse2001ResultadoBeneficiarioFinal;
import br.com.fidias.sicoob_cobranca.model.RateioCredito;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Boleto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class Boleto {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_CODIGO_MODALIDADE = "codigoModalidade";
  @SerializedName(SERIALIZED_NAME_CODIGO_MODALIDADE)
  private Integer codigoModalidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTA_CORRENTE = "numeroContaCorrente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTA_CORRENTE)
  private Integer numeroContaCorrente;

  public static final String SERIALIZED_NAME_CODIGO_ESPECIE_DOCUMENTO = "codigoEspecieDocumento";
  @SerializedName(SERIALIZED_NAME_CODIGO_ESPECIE_DOCUMENTO)
  private String codigoEspecieDocumento;

  public static final String SERIALIZED_NAME_DATA_EMISSAO = "dataEmissao";
  @SerializedName(SERIALIZED_NAME_DATA_EMISSAO)
  private LocalDate dataEmissao;

  public static final String SERIALIZED_NAME_NOSSO_NUMERO = "nossoNumero";
  @SerializedName(SERIALIZED_NAME_NOSSO_NUMERO)
  private Integer nossoNumero;

  public static final String SERIALIZED_NAME_SEU_NUMERO = "seuNumero";
  @SerializedName(SERIALIZED_NAME_SEU_NUMERO)
  private String seuNumero;

  public static final String SERIALIZED_NAME_IDENTIFICACAO_BOLETO_EMPRESA = "identificacaoBoletoEmpresa";
  @SerializedName(SERIALIZED_NAME_IDENTIFICACAO_BOLETO_EMPRESA)
  private String identificacaoBoletoEmpresa;

  public static final String SERIALIZED_NAME_IDENTIFICACAO_EMISSAO_BOLETO = "identificacaoEmissaoBoleto";
  @SerializedName(SERIALIZED_NAME_IDENTIFICACAO_EMISSAO_BOLETO)
  private Integer identificacaoEmissaoBoleto;

  public static final String SERIALIZED_NAME_IDENTIFICACAO_DISTRIBUICAO_BOLETO = "identificacaoDistribuicaoBoleto";
  @SerializedName(SERIALIZED_NAME_IDENTIFICACAO_DISTRIBUICAO_BOLETO)
  private Integer identificacaoDistribuicaoBoleto;

  public static final String SERIALIZED_NAME_VALOR = "valor";
  @SerializedName(SERIALIZED_NAME_VALOR)
  private Double valor;

  public static final String SERIALIZED_NAME_DATA_VENCIMENTO = "dataVencimento";
  @SerializedName(SERIALIZED_NAME_DATA_VENCIMENTO)
  private LocalDate dataVencimento;

  public static final String SERIALIZED_NAME_DATA_LIMITE_PAGAMENTO = "dataLimitePagamento";
  @SerializedName(SERIALIZED_NAME_DATA_LIMITE_PAGAMENTO)
  private LocalDate dataLimitePagamento;

  public static final String SERIALIZED_NAME_VALOR_ABATIMENTO = "valorAbatimento";
  @SerializedName(SERIALIZED_NAME_VALOR_ABATIMENTO)
  private Double valorAbatimento;

  public static final String SERIALIZED_NAME_TIPO_DESCONTO = "tipoDesconto";
  @SerializedName(SERIALIZED_NAME_TIPO_DESCONTO)
  private Long tipoDesconto;

  public static final String SERIALIZED_NAME_DATA_PRIMEIRO_DESCONTO = "dataPrimeiroDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_PRIMEIRO_DESCONTO)
  private LocalDate dataPrimeiroDesconto;

  public static final String SERIALIZED_NAME_VALOR_PRIMEIRO_DESCONTO = "valorPrimeiroDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_PRIMEIRO_DESCONTO)
  private Double valorPrimeiroDesconto;

  public static final String SERIALIZED_NAME_DATA_SEGUNDO_DESCONTO = "dataSegundoDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_SEGUNDO_DESCONTO)
  private LocalDate dataSegundoDesconto;

  public static final String SERIALIZED_NAME_VALOR_SEGUNDO_DESCONTO = "valorSegundoDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_SEGUNDO_DESCONTO)
  private Double valorSegundoDesconto;

  public static final String SERIALIZED_NAME_DATA_TERCEIRO_DESCONTO = "dataTerceiroDesconto";
  @SerializedName(SERIALIZED_NAME_DATA_TERCEIRO_DESCONTO)
  private LocalDate dataTerceiroDesconto;

  public static final String SERIALIZED_NAME_VALOR_TERCEIRO_DESCONTO = "valorTerceiroDesconto";
  @SerializedName(SERIALIZED_NAME_VALOR_TERCEIRO_DESCONTO)
  private Double valorTerceiroDesconto;

  public static final String SERIALIZED_NAME_TIPO_MULTA = "tipoMulta";
  @SerializedName(SERIALIZED_NAME_TIPO_MULTA)
  private Integer tipoMulta;

  public static final String SERIALIZED_NAME_DATA_MULTA = "dataMulta";
  @SerializedName(SERIALIZED_NAME_DATA_MULTA)
  private LocalDate dataMulta;

  public static final String SERIALIZED_NAME_VALOR_MULTA = "valorMulta";
  @SerializedName(SERIALIZED_NAME_VALOR_MULTA)
  private Double valorMulta;

  public static final String SERIALIZED_NAME_TIPO_JUROS_MORA = "tipoJurosMora";
  @SerializedName(SERIALIZED_NAME_TIPO_JUROS_MORA)
  private Integer tipoJurosMora;

  public static final String SERIALIZED_NAME_DATA_JUROS_MORA = "dataJurosMora";
  @SerializedName(SERIALIZED_NAME_DATA_JUROS_MORA)
  private LocalDate dataJurosMora;

  public static final String SERIALIZED_NAME_VALOR_JUROS_MORA = "valorJurosMora";
  @SerializedName(SERIALIZED_NAME_VALOR_JUROS_MORA)
  private Double valorJurosMora;

  public static final String SERIALIZED_NAME_NUMERO_PARCELA = "numeroParcela";
  @SerializedName(SERIALIZED_NAME_NUMERO_PARCELA)
  private Long numeroParcela;

  public static final String SERIALIZED_NAME_ACEITE = "aceite";
  @SerializedName(SERIALIZED_NAME_ACEITE)
  private Boolean aceite;

  public static final String SERIALIZED_NAME_CODIGO_NEGATIVACAO = "codigoNegativacao";
  @SerializedName(SERIALIZED_NAME_CODIGO_NEGATIVACAO)
  private Integer codigoNegativacao;

  public static final String SERIALIZED_NAME_NUMERO_DIAS_NEGATIVACAO = "numeroDiasNegativacao";
  @SerializedName(SERIALIZED_NAME_NUMERO_DIAS_NEGATIVACAO)
  private Integer numeroDiasNegativacao;

  public static final String SERIALIZED_NAME_CODIGO_PROTESTO = "codigoProtesto";
  @SerializedName(SERIALIZED_NAME_CODIGO_PROTESTO)
  private Integer codigoProtesto;

  public static final String SERIALIZED_NAME_NUMERO_DIAS_PROTESTO = "numeroDiasProtesto";
  @SerializedName(SERIALIZED_NAME_NUMERO_DIAS_PROTESTO)
  private Integer numeroDiasProtesto;

  public static final String SERIALIZED_NAME_PAGADOR = "pagador";
  @SerializedName(SERIALIZED_NAME_PAGADOR)
  private BoletoPagador pagador;

  public static final String SERIALIZED_NAME_BENEFICIARIO_FINAL = "beneficiarioFinal";
  @SerializedName(SERIALIZED_NAME_BENEFICIARIO_FINAL)
  private InlineResponse2001ResultadoBeneficiarioFinal beneficiarioFinal;

  public static final String SERIALIZED_NAME_MENSAGENS_INSTRUCAO = "mensagensInstrucao";
  @SerializedName(SERIALIZED_NAME_MENSAGENS_INSTRUCAO)
  private List<String> mensagensInstrucao = null;

  public static final String SERIALIZED_NAME_GERAR_PDF = "gerarPdf";
  @SerializedName(SERIALIZED_NAME_GERAR_PDF)
  private Boolean gerarPdf;

  public static final String SERIALIZED_NAME_RATEIO_CREDITOS = "rateioCreditos";
  @SerializedName(SERIALIZED_NAME_RATEIO_CREDITOS)
  private List<RateioCredito> rateioCreditos = null;

  public static final String SERIALIZED_NAME_CODIGO_CADASTRAR_P_I_X = "codigoCadastrarPIX";
  @SerializedName(SERIALIZED_NAME_CODIGO_CADASTRAR_P_I_X)
  private Integer codigoCadastrarPIX;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  private Long numeroContratoCobranca;


  public Boleto numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário no Sisbr.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "25546454", required = true, value = "Número que identifica o contrato do beneficiário no Sisbr.")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public Boleto codigoModalidade(Integer codigoModalidade) {
    
    this.codigoModalidade = codigoModalidade;
    return this;
  }

   /**
   * Número que identifica a modalidade do boleto. Informar - 1 - SIMPLES COM REGISTRO
   * @return codigoModalidade
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número que identifica a modalidade do boleto. Informar - 1 - SIMPLES COM REGISTRO")

  public Integer getCodigoModalidade() {
    return codigoModalidade;
  }


  public void setCodigoModalidade(Integer codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }


  public Boleto numeroContaCorrente(Integer numeroContaCorrente) {
    
    this.numeroContaCorrente = numeroContaCorrente;
    return this;
  }

   /**
   * Número da Conta Corrente onde será realizado o crédito da liquidação do boleto.
   * @return numeroContaCorrente
  **/
  @ApiModelProperty(example = "123456", required = true, value = "Número da Conta Corrente onde será realizado o crédito da liquidação do boleto.")

  public Integer getNumeroContaCorrente() {
    return numeroContaCorrente;
  }


  public void setNumeroContaCorrente(Integer numeroContaCorrente) {
    this.numeroContaCorrente = numeroContaCorrente;
  }


  public Boleto codigoEspecieDocumento(String codigoEspecieDocumento) {
    
    this.codigoEspecieDocumento = codigoEspecieDocumento;
    return this;
  }

   /**
   * Espécie do Documento. Informar valores listados abaixo. &#x60;Tamanho máximo 3&#x60;   - CH - Cheque   - DM - Duplicata Mercantil   - DMI - Duplicata Mercantil Indicação   - DS - Duplicata de Serviço   - DSI - Duplicata Serviço Indicação   - DR - Duplicata Rural   - LC - Letra de Câmbio   - NCC - Nota de Crédito Comercial   - NCE - Nota de Crédito Exportação   - NCI - Nota de Crédito Industrial   - NCR - Nota de Crédito Rural   - NP - Nota Promissória   - NPR - Nota Promissória Rural   - TM - Triplicata Mercantil   - TS - Triplicata de Serviço   - NS - Nota de Seguro   - RC - Recibo   - FAT - Fatura   - ND - Nota de Débito   - AP - Apólice de Seguro   - ME - Mensalidade Escolar   - PC - Pagamento de Consórcio   - NF - Nota Fiscal   - DD - Documento de Dívida   - BDP - Boleto Proposta   - OU - Outros
   * @return codigoEspecieDocumento
  **/
  @ApiModelProperty(example = "DM", required = true, value = "Espécie do Documento. Informar valores listados abaixo. `Tamanho máximo 3`   - CH - Cheque   - DM - Duplicata Mercantil   - DMI - Duplicata Mercantil Indicação   - DS - Duplicata de Serviço   - DSI - Duplicata Serviço Indicação   - DR - Duplicata Rural   - LC - Letra de Câmbio   - NCC - Nota de Crédito Comercial   - NCE - Nota de Crédito Exportação   - NCI - Nota de Crédito Industrial   - NCR - Nota de Crédito Rural   - NP - Nota Promissória   - NPR - Nota Promissória Rural   - TM - Triplicata Mercantil   - TS - Triplicata de Serviço   - NS - Nota de Seguro   - RC - Recibo   - FAT - Fatura   - ND - Nota de Débito   - AP - Apólice de Seguro   - ME - Mensalidade Escolar   - PC - Pagamento de Consórcio   - NF - Nota Fiscal   - DD - Documento de Dívida   - BDP - Boleto Proposta   - OU - Outros")

  public String getCodigoEspecieDocumento() {
    return codigoEspecieDocumento;
  }


  public void setCodigoEspecieDocumento(String codigoEspecieDocumento) {
    this.codigoEspecieDocumento = codigoEspecieDocumento;
  }


  public Boleto dataEmissao(LocalDate dataEmissao) {
    
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Data de emissão do boleto. Formato: yyyy-MM-dd
   * @return dataEmissao
  **/
  @ApiModelProperty(example = "Sun Aug 31 21:00:00 BRT 2025", required = true, value = "Data de emissão do boleto. Formato: yyyy-MM-dd")

  public LocalDate getDataEmissao() {
    return dataEmissao;
  }


  public void setDataEmissao(LocalDate dataEmissao) {
    this.dataEmissao = dataEmissao;
  }


  public Boleto nossoNumero(Integer nossoNumero) {
    
    this.nossoNumero = nossoNumero;
    return this;
  }

   /**
   * Número que identifica o boleto de cobrança no Sisbr. Caso deseje, o beneficiário poderá informar o nossoNumero.
   * @return nossoNumero
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123456789012345678", value = "Número que identifica o boleto de cobrança no Sisbr. Caso deseje, o beneficiário poderá informar o nossoNumero.")

  public Integer getNossoNumero() {
    return nossoNumero;
  }


  public void setNossoNumero(Integer nossoNumero) {
    this.nossoNumero = nossoNumero;
  }


  public Boleto seuNumero(String seuNumero) {
    
    this.seuNumero = seuNumero;
    return this;
  }

   /**
   * Número identificador do boleto no sistema do beneficiário. &#x60;Tamanho máximo 18&#x60;
   * @return seuNumero
  **/
  @ApiModelProperty(example = "012345678901234567", required = true, value = "Número identificador do boleto no sistema do beneficiário. `Tamanho máximo 18`")

  public String getSeuNumero() {
    return seuNumero;
  }


  public void setSeuNumero(String seuNumero) {
    this.seuNumero = seuNumero;
  }


  public Boleto identificacaoBoletoEmpresa(String identificacaoBoletoEmpresa) {
    
    this.identificacaoBoletoEmpresa = identificacaoBoletoEmpresa;
    return this;
  }

   /**
   * Campo destinado para uso da empresa do beneficiário para identificação do boleto. &#x60;Tamanho máximo 25&#x60;
   * @return identificacaoBoletoEmpresa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "01234567890123456789", value = "Campo destinado para uso da empresa do beneficiário para identificação do boleto. `Tamanho máximo 25`")

  public String getIdentificacaoBoletoEmpresa() {
    return identificacaoBoletoEmpresa;
  }


  public void setIdentificacaoBoletoEmpresa(String identificacaoBoletoEmpresa) {
    this.identificacaoBoletoEmpresa = identificacaoBoletoEmpresa;
  }


  public Boleto identificacaoEmissaoBoleto(Integer identificacaoEmissaoBoleto) {
    
    this.identificacaoEmissaoBoleto = identificacaoEmissaoBoleto;
    return this;
  }

   /**
   * Código de identificação de emissão do boleto. Informar os valores listados abaixo. - 1 Banco Emite - 2 Cliente Emite
   * @return identificacaoEmissaoBoleto
  **/
  @ApiModelProperty(example = "1", required = true, value = "Código de identificação de emissão do boleto. Informar os valores listados abaixo. - 1 Banco Emite - 2 Cliente Emite")

  public Integer getIdentificacaoEmissaoBoleto() {
    return identificacaoEmissaoBoleto;
  }


  public void setIdentificacaoEmissaoBoleto(Integer identificacaoEmissaoBoleto) {
    this.identificacaoEmissaoBoleto = identificacaoEmissaoBoleto;
  }


  public Boleto identificacaoDistribuicaoBoleto(Integer identificacaoDistribuicaoBoleto) {
    
    this.identificacaoDistribuicaoBoleto = identificacaoDistribuicaoBoleto;
    return this;
  }

   /**
   * Código de identificação de distribuição do boleto. Informar os valores listados abaixo. - 1 Banco Distribui - 2 Cliente Distribui
   * @return identificacaoDistribuicaoBoleto
  **/
  @ApiModelProperty(example = "1", required = true, value = "Código de identificação de distribuição do boleto. Informar os valores listados abaixo. - 1 Banco Distribui - 2 Cliente Distribui")

  public Integer getIdentificacaoDistribuicaoBoleto() {
    return identificacaoDistribuicaoBoleto;
  }


  public void setIdentificacaoDistribuicaoBoleto(Integer identificacaoDistribuicaoBoleto) {
    this.identificacaoDistribuicaoBoleto = identificacaoDistribuicaoBoleto;
  }


  public Boleto valor(Double valor) {
    
    this.valor = valor;
    return this;
  }

   /**
   * Valor nominal do boleto.
   * @return valor
  **/
  @ApiModelProperty(example = "156.23", required = true, value = "Valor nominal do boleto.")

  public Double getValor() {
    return valor;
  }


  public void setValor(Double valor) {
    this.valor = valor;
  }


  public Boleto dataVencimento(LocalDate dataVencimento) {
    
    this.dataVencimento = dataVencimento;
    return this;
  }

   /**
   * Data de vencimento do boleto.   Formato: yyyy-MM-dd 
   * @return dataVencimento
  **/
  @ApiModelProperty(example = "Wed Sep 24 21:00:00 BRT 2025", required = true, value = "Data de vencimento do boleto.   Formato: yyyy-MM-dd ")

  public LocalDate getDataVencimento() {
    return dataVencimento;
  }


  public void setDataVencimento(LocalDate dataVencimento) {
    this.dataVencimento = dataVencimento;
  }


  public Boleto dataLimitePagamento(LocalDate dataLimitePagamento) {
    
    this.dataLimitePagamento = dataLimitePagamento;
    return this;
  }

   /**
   * Data de limite para pagamento do boleto. Formato: yyyy-MM-dd 
   * @return dataLimitePagamento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Nov 04 21:00:00 BRT 2025", value = "Data de limite para pagamento do boleto. Formato: yyyy-MM-dd ")

  public LocalDate getDataLimitePagamento() {
    return dataLimitePagamento;
  }


  public void setDataLimitePagamento(LocalDate dataLimitePagamento) {
    this.dataLimitePagamento = dataLimitePagamento;
  }


  public Boleto valorAbatimento(Double valorAbatimento) {
    
    this.valorAbatimento = valorAbatimento;
    return this;
  }

   /**
   * Valor do abatimento a ser aplicado no boleto.
   * @return valorAbatimento
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.57", value = "Valor do abatimento a ser aplicado no boleto.")

  public Double getValorAbatimento() {
    return valorAbatimento;
  }


  public void setValorAbatimento(Double valorAbatimento) {
    this.valorAbatimento = valorAbatimento;
  }


  public Boleto tipoDesconto(Long tipoDesconto) {
    
    this.tipoDesconto = tipoDesconto;
    return this;
  }

   /**
   * Informar o tipo de desconto atribuido ao boleto.                   - 0 Sem Desconto                   - 1 Valor Fixo Até a Data Informada                   - 2 Percentual até a data informada                   - 3 Valor por antecipação dia corrido                   - 4 Valor por antecipação dia útil                   - 5 Percentual por antecipação dia corrido                   - 6 Percentual por antecipação dia útil
   * @return tipoDesconto
  **/
  @ApiModelProperty(example = "1", required = true, value = "Informar o tipo de desconto atribuido ao boleto.                   - 0 Sem Desconto                   - 1 Valor Fixo Até a Data Informada                   - 2 Percentual até a data informada                   - 3 Valor por antecipação dia corrido                   - 4 Valor por antecipação dia útil                   - 5 Percentual por antecipação dia corrido                   - 6 Percentual por antecipação dia útil")

  public Long getTipoDesconto() {
    return tipoDesconto;
  }


  public void setTipoDesconto(Long tipoDesconto) {
    this.tipoDesconto = tipoDesconto;
  }


  public Boleto dataPrimeiroDesconto(LocalDate dataPrimeiroDesconto) {
    
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
    return this;
  }

   /**
   * Data do primeiro desconto. Deve ser informado caso o tipo de desconto seja diferente de 0. Formato: yyyy-MM-dd 
   * @return dataPrimeiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sun Sep 14 21:00:00 BRT 2025", value = "Data do primeiro desconto. Deve ser informado caso o tipo de desconto seja diferente de 0. Formato: yyyy-MM-dd ")

  public LocalDate getDataPrimeiroDesconto() {
    return dataPrimeiroDesconto;
  }


  public void setDataPrimeiroDesconto(LocalDate dataPrimeiroDesconto) {
    this.dataPrimeiroDesconto = dataPrimeiroDesconto;
  }


  public Boleto valorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
    return this;
  }

   /**
   * Valor do primeiro desconto. Deve ser informado caso a data do primeiro desconto seja preenchida.
   * @return valorPrimeiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "22.5", value = "Valor do primeiro desconto. Deve ser informado caso a data do primeiro desconto seja preenchida.")

  public Double getValorPrimeiroDesconto() {
    return valorPrimeiroDesconto;
  }


  public void setValorPrimeiroDesconto(Double valorPrimeiroDesconto) {
    this.valorPrimeiroDesconto = valorPrimeiroDesconto;
  }


  public Boleto dataSegundoDesconto(LocalDate dataSegundoDesconto) {
    
    this.dataSegundoDesconto = dataSegundoDesconto;
    return this;
  }

   /**
   * Data do segundo desconto. Formato: yyyy-MM-dd 
   * @return dataSegundoDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Fri Sep 19 21:00:00 BRT 2025", value = "Data do segundo desconto. Formato: yyyy-MM-dd ")

  public LocalDate getDataSegundoDesconto() {
    return dataSegundoDesconto;
  }


  public void setDataSegundoDesconto(LocalDate dataSegundoDesconto) {
    this.dataSegundoDesconto = dataSegundoDesconto;
  }


  public Boleto valorSegundoDesconto(Double valorSegundoDesconto) {
    
    this.valorSegundoDesconto = valorSegundoDesconto;
    return this;
  }

   /**
   * Valor do segundo desconto. Deve ser informado caso a data do segundo desconto seja preenchida.
   * @return valorSegundoDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "15.5", value = "Valor do segundo desconto. Deve ser informado caso a data do segundo desconto seja preenchida.")

  public Double getValorSegundoDesconto() {
    return valorSegundoDesconto;
  }


  public void setValorSegundoDesconto(Double valorSegundoDesconto) {
    this.valorSegundoDesconto = valorSegundoDesconto;
  }


  public Boleto dataTerceiroDesconto(LocalDate dataTerceiroDesconto) {
    
    this.dataTerceiroDesconto = dataTerceiroDesconto;
    return this;
  }

   /**
   * Data do terceiro desconto. Formato: yyyy-MM-dd 
   * @return dataTerceiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Sep 23 21:00:00 BRT 2025", value = "Data do terceiro desconto. Formato: yyyy-MM-dd ")

  public LocalDate getDataTerceiroDesconto() {
    return dataTerceiroDesconto;
  }


  public void setDataTerceiroDesconto(LocalDate dataTerceiroDesconto) {
    this.dataTerceiroDesconto = dataTerceiroDesconto;
  }


  public Boleto valorTerceiroDesconto(Double valorTerceiroDesconto) {
    
    this.valorTerceiroDesconto = valorTerceiroDesconto;
    return this;
  }

   /**
   * Valor do terceiro desconto.Deve ser preenchido caso a data do terceiro desconto seja preenchida.
   * @return valorTerceiroDesconto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10.5", value = "Valor do terceiro desconto.Deve ser preenchido caso a data do terceiro desconto seja preenchida.")

  public Double getValorTerceiroDesconto() {
    return valorTerceiroDesconto;
  }


  public void setValorTerceiroDesconto(Double valorTerceiroDesconto) {
    this.valorTerceiroDesconto = valorTerceiroDesconto;
  }


  public Boleto tipoMulta(Integer tipoMulta) {
    
    this.tipoMulta = tipoMulta;
    return this;
  }

   /**
   * Tipo de multa a ser aplicado no boleto. Informar os valores listados abaixo.   - 0 Isento   - 1 Valor Fixo   - 2 Percentual
   * @return tipoMulta
  **/
  @ApiModelProperty(example = "1", required = true, value = "Tipo de multa a ser aplicado no boleto. Informar os valores listados abaixo.   - 0 Isento   - 1 Valor Fixo   - 2 Percentual")

  public Integer getTipoMulta() {
    return tipoMulta;
  }


  public void setTipoMulta(Integer tipoMulta) {
    this.tipoMulta = tipoMulta;
  }


  public Boleto dataMulta(LocalDate dataMulta) {
    
    this.dataMulta = dataMulta;
    return this;
  }

   /**
   * Deve ser maior que a data de vencimento do boleto e menor ou igual que data limite de pagamento. Formato: yyyy-MM-dd
   * @return dataMulta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Nov 04 21:00:00 BRT 2025", value = "Deve ser maior que a data de vencimento do boleto e menor ou igual que data limite de pagamento. Formato: yyyy-MM-dd")

  public LocalDate getDataMulta() {
    return dataMulta;
  }


  public void setDataMulta(LocalDate dataMulta) {
    this.dataMulta = dataMulta;
  }


  public Boleto valorMulta(Double valorMulta) {
    
    this.valorMulta = valorMulta;
    return this;
  }

   /**
   * Valor da multa. Deve ser preenchido caso o campo dataMulta seja preenchido.
   * @return valorMulta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.5", value = "Valor da multa. Deve ser preenchido caso o campo dataMulta seja preenchido.")

  public Double getValorMulta() {
    return valorMulta;
  }


  public void setValorMulta(Double valorMulta) {
    this.valorMulta = valorMulta;
  }


  public Boleto tipoJurosMora(Integer tipoJurosMora) {
    
    this.tipoJurosMora = tipoJurosMora;
    return this;
  }

   /**
   * Tipo de juros de mora. Informar os valores listados abaixo.   - 1 Valor por dia   - 2 Taxa Mensal   - 3 Isento
   * @return tipoJurosMora
  **/
  @ApiModelProperty(example = "1", required = true, value = "Tipo de juros de mora. Informar os valores listados abaixo.   - 1 Valor por dia   - 2 Taxa Mensal   - 3 Isento")

  public Integer getTipoJurosMora() {
    return tipoJurosMora;
  }


  public void setTipoJurosMora(Integer tipoJurosMora) {
    this.tipoJurosMora = tipoJurosMora;
  }


  public Boleto dataJurosMora(LocalDate dataJurosMora) {
    
    this.dataJurosMora = dataJurosMora;
    return this;
  }

   /**
   * Deve ser maior que a data de vencimento do boleto e menor ou igual que data limite de pagamento. Formato: yyyy-MM-dd
   * @return dataJurosMora
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Tue Nov 04 21:00:00 BRT 2025", value = "Deve ser maior que a data de vencimento do boleto e menor ou igual que data limite de pagamento. Formato: yyyy-MM-dd")

  public LocalDate getDataJurosMora() {
    return dataJurosMora;
  }


  public void setDataJurosMora(LocalDate dataJurosMora) {
    this.dataJurosMora = dataJurosMora;
  }


  public Boleto valorJurosMora(Double valorJurosMora) {
    
    this.valorJurosMora = valorJurosMora;
    return this;
  }

   /**
   * Valor do juros de mora. Deve ser preenchido caso o campo dataJurosMora seja preenchido.
   * @return valorJurosMora
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4.5", value = "Valor do juros de mora. Deve ser preenchido caso o campo dataJurosMora seja preenchido.")

  public Double getValorJurosMora() {
    return valorJurosMora;
  }


  public void setValorJurosMora(Double valorJurosMora) {
    this.valorJurosMora = valorJurosMora;
  }


  public Boleto numeroParcela(Long numeroParcela) {
    
    this.numeroParcela = numeroParcela;
    return this;
  }

   /**
   * Número da parcela do boleto.Valor máximo permitido &#39;99&#39;.
   * @return numeroParcela
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número da parcela do boleto.Valor máximo permitido '99'.")

  public Long getNumeroParcela() {
    return numeroParcela;
  }


  public void setNumeroParcela(Long numeroParcela) {
    this.numeroParcela = numeroParcela;
  }


  public Boleto aceite(Boolean aceite) {
    
    this.aceite = aceite;
    return this;
  }

   /**
   * Identificador do aceite do boleto.
   * @return aceite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Identificador do aceite do boleto.")

  public Boolean getAceite() {
    return aceite;
  }


  public void setAceite(Boolean aceite) {
    this.aceite = aceite;
  }


  public Boleto codigoNegativacao(Integer codigoNegativacao) {
    
    this.codigoNegativacao = codigoNegativacao;
    return this;
  }

   /**
   * Código de negativação do boleto. Informar os valores abaixo.   - 2 Negativar Dias Úteis   - 3 Não Negativar
   * @return codigoNegativacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2", value = "Código de negativação do boleto. Informar os valores abaixo.   - 2 Negativar Dias Úteis   - 3 Não Negativar")

  public Integer getCodigoNegativacao() {
    return codigoNegativacao;
  }


  public void setCodigoNegativacao(Integer codigoNegativacao) {
    this.codigoNegativacao = codigoNegativacao;
  }


  public Boleto numeroDiasNegativacao(Integer numeroDiasNegativacao) {
    
    this.numeroDiasNegativacao = numeroDiasNegativacao;
    return this;
  }

   /**
   * Número de dias para negativação do boleto. Deve ser preenchido caso o campo codigoNegativacao seja igual a &#39;2&#39;. &#x60;Tamanho máximo 99&#x60;
   * @return numeroDiasNegativacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "60", value = "Número de dias para negativação do boleto. Deve ser preenchido caso o campo codigoNegativacao seja igual a '2'. `Tamanho máximo 99`")

  public Integer getNumeroDiasNegativacao() {
    return numeroDiasNegativacao;
  }


  public void setNumeroDiasNegativacao(Integer numeroDiasNegativacao) {
    this.numeroDiasNegativacao = numeroDiasNegativacao;
  }


  public Boleto codigoProtesto(Integer codigoProtesto) {
    
    this.codigoProtesto = codigoProtesto;
    return this;
  }

   /**
   * Código de protesto do boleto. Informar os valores abaixo.   - 1 Protestar Dias Corridos   - 2 Protestar Dias Úteis   - 3 Não Protestar
   * @return codigoProtesto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Código de protesto do boleto. Informar os valores abaixo.   - 1 Protestar Dias Corridos   - 2 Protestar Dias Úteis   - 3 Não Protestar")

  public Integer getCodigoProtesto() {
    return codigoProtesto;
  }


  public void setCodigoProtesto(Integer codigoProtesto) {
    this.codigoProtesto = codigoProtesto;
  }


  public Boleto numeroDiasProtesto(Integer numeroDiasProtesto) {
    
    this.numeroDiasProtesto = numeroDiasProtesto;
    return this;
  }

   /**
   * Número de dias para protesto do boleto. Deve ser preenchido caso o campo codigoProtesto seja &#39;1&#39;. &#x60;Tamanho máximo 99&#x60;
   * @return numeroDiasProtesto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "30", value = "Número de dias para protesto do boleto. Deve ser preenchido caso o campo codigoProtesto seja '1'. `Tamanho máximo 99`")

  public Integer getNumeroDiasProtesto() {
    return numeroDiasProtesto;
  }


  public void setNumeroDiasProtesto(Integer numeroDiasProtesto) {
    this.numeroDiasProtesto = numeroDiasProtesto;
  }


  public Boleto pagador(BoletoPagador pagador) {
    
    this.pagador = pagador;
    return this;
  }

   /**
   * Get pagador
   * @return pagador
  **/
  @ApiModelProperty(required = true, value = "")

  public BoletoPagador getPagador() {
    return pagador;
  }


  public void setPagador(BoletoPagador pagador) {
    this.pagador = pagador;
  }


  public Boleto beneficiarioFinal(InlineResponse2001ResultadoBeneficiarioFinal beneficiarioFinal) {
    
    this.beneficiarioFinal = beneficiarioFinal;
    return this;
  }

   /**
   * Get beneficiarioFinal
   * @return beneficiarioFinal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InlineResponse2001ResultadoBeneficiarioFinal getBeneficiarioFinal() {
    return beneficiarioFinal;
  }


  public void setBeneficiarioFinal(InlineResponse2001ResultadoBeneficiarioFinal beneficiarioFinal) {
    this.beneficiarioFinal = beneficiarioFinal;
  }


  public Boleto mensagensInstrucao(List<String> mensagensInstrucao) {
    
    this.mensagensInstrucao = mensagensInstrucao;
    return this;
  }

  public Boleto addMensagensInstrucaoItem(String mensagensInstrucaoItem) {
    if (this.mensagensInstrucao == null) {
      this.mensagensInstrucao = new ArrayList<>();
    }
    this.mensagensInstrucao.add(mensagensInstrucaoItem);
    return this;
  }

   /**
   * Get mensagensInstrucao
   * @return mensagensInstrucao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[Descrição da Instrução 1, Descrição da Instrução 2, Descrição da Instrução 3, Descrição da Instrução 4, Descrição da Instrução 5]", value = "")

  public List<String> getMensagensInstrucao() {
    return mensagensInstrucao;
  }


  public void setMensagensInstrucao(List<String> mensagensInstrucao) {
    this.mensagensInstrucao = mensagensInstrucao;
  }


  public Boleto gerarPdf(Boolean gerarPdf) {
    
    this.gerarPdf = gerarPdf;
    return this;
  }

   /**
   * Identificador para o sistema devolver ou não o PDF do Boleto. O PDF será retornado na Base64.
   * @return gerarPdf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Identificador para o sistema devolver ou não o PDF do Boleto. O PDF será retornado na Base64.")

  public Boolean getGerarPdf() {
    return gerarPdf;
  }


  public void setGerarPdf(Boolean gerarPdf) {
    this.gerarPdf = gerarPdf;
  }


  public Boleto rateioCreditos(List<RateioCredito> rateioCreditos) {
    
    this.rateioCreditos = rateioCreditos;
    return this;
  }

  public Boleto addRateioCreditosItem(RateioCredito rateioCreditosItem) {
    if (this.rateioCreditos == null) {
      this.rateioCreditos = new ArrayList<>();
    }
    this.rateioCreditos.add(rateioCreditosItem);
    return this;
  }

   /**
   * Get rateioCreditos
   * @return rateioCreditos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<RateioCredito> getRateioCreditos() {
    return rateioCreditos;
  }


  public void setRateioCreditos(List<RateioCredito> rateioCreditos) {
    this.rateioCreditos = rateioCreditos;
  }


  public Boleto codigoCadastrarPIX(Integer codigoCadastrarPIX) {
    
    this.codigoCadastrarPIX = codigoCadastrarPIX;
    return this;
  }

   /**
   * Indicar uma das opções - 0 Padrão - 1 Com Pix - 2 Sem Pix
   * @return codigoCadastrarPIX
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Indicar uma das opções - 0 Padrão - 1 Com Pix - 2 Sem Pix")

  public Integer getCodigoCadastrarPIX() {
    return codigoCadastrarPIX;
  }


  public void setCodigoCadastrarPIX(Integer codigoCadastrarPIX) {
    this.codigoCadastrarPIX = codigoCadastrarPIX;
  }


  public Boleto numeroContratoCobranca(Long numeroContratoCobranca) {
    
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Indicar o id do contrato Cobranca
   * @return numeroContratoCobranca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Indicar o id do contrato Cobranca")

  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }


  public void setNumeroContratoCobranca(Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Boleto boleto = (Boleto) o;
    return Objects.equals(this.numeroCliente, boleto.numeroCliente) &&
        Objects.equals(this.codigoModalidade, boleto.codigoModalidade) &&
        Objects.equals(this.numeroContaCorrente, boleto.numeroContaCorrente) &&
        Objects.equals(this.codigoEspecieDocumento, boleto.codigoEspecieDocumento) &&
        Objects.equals(this.dataEmissao, boleto.dataEmissao) &&
        Objects.equals(this.nossoNumero, boleto.nossoNumero) &&
        Objects.equals(this.seuNumero, boleto.seuNumero) &&
        Objects.equals(this.identificacaoBoletoEmpresa, boleto.identificacaoBoletoEmpresa) &&
        Objects.equals(this.identificacaoEmissaoBoleto, boleto.identificacaoEmissaoBoleto) &&
        Objects.equals(this.identificacaoDistribuicaoBoleto, boleto.identificacaoDistribuicaoBoleto) &&
        Objects.equals(this.valor, boleto.valor) &&
        Objects.equals(this.dataVencimento, boleto.dataVencimento) &&
        Objects.equals(this.dataLimitePagamento, boleto.dataLimitePagamento) &&
        Objects.equals(this.valorAbatimento, boleto.valorAbatimento) &&
        Objects.equals(this.tipoDesconto, boleto.tipoDesconto) &&
        Objects.equals(this.dataPrimeiroDesconto, boleto.dataPrimeiroDesconto) &&
        Objects.equals(this.valorPrimeiroDesconto, boleto.valorPrimeiroDesconto) &&
        Objects.equals(this.dataSegundoDesconto, boleto.dataSegundoDesconto) &&
        Objects.equals(this.valorSegundoDesconto, boleto.valorSegundoDesconto) &&
        Objects.equals(this.dataTerceiroDesconto, boleto.dataTerceiroDesconto) &&
        Objects.equals(this.valorTerceiroDesconto, boleto.valorTerceiroDesconto) &&
        Objects.equals(this.tipoMulta, boleto.tipoMulta) &&
        Objects.equals(this.dataMulta, boleto.dataMulta) &&
        Objects.equals(this.valorMulta, boleto.valorMulta) &&
        Objects.equals(this.tipoJurosMora, boleto.tipoJurosMora) &&
        Objects.equals(this.dataJurosMora, boleto.dataJurosMora) &&
        Objects.equals(this.valorJurosMora, boleto.valorJurosMora) &&
        Objects.equals(this.numeroParcela, boleto.numeroParcela) &&
        Objects.equals(this.aceite, boleto.aceite) &&
        Objects.equals(this.codigoNegativacao, boleto.codigoNegativacao) &&
        Objects.equals(this.numeroDiasNegativacao, boleto.numeroDiasNegativacao) &&
        Objects.equals(this.codigoProtesto, boleto.codigoProtesto) &&
        Objects.equals(this.numeroDiasProtesto, boleto.numeroDiasProtesto) &&
        Objects.equals(this.pagador, boleto.pagador) &&
        Objects.equals(this.beneficiarioFinal, boleto.beneficiarioFinal) &&
        Objects.equals(this.mensagensInstrucao, boleto.mensagensInstrucao) &&
        Objects.equals(this.gerarPdf, boleto.gerarPdf) &&
        Objects.equals(this.rateioCreditos, boleto.rateioCreditos) &&
        Objects.equals(this.codigoCadastrarPIX, boleto.codigoCadastrarPIX) &&
        Objects.equals(this.numeroContratoCobranca, boleto.numeroContratoCobranca);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, codigoModalidade, numeroContaCorrente, codigoEspecieDocumento, dataEmissao, nossoNumero, seuNumero, identificacaoBoletoEmpresa, identificacaoEmissaoBoleto, identificacaoDistribuicaoBoleto, valor, dataVencimento, dataLimitePagamento, valorAbatimento, tipoDesconto, dataPrimeiroDesconto, valorPrimeiroDesconto, dataSegundoDesconto, valorSegundoDesconto, dataTerceiroDesconto, valorTerceiroDesconto, tipoMulta, dataMulta, valorMulta, tipoJurosMora, dataJurosMora, valorJurosMora, numeroParcela, aceite, codigoNegativacao, numeroDiasNegativacao, codigoProtesto, numeroDiasProtesto, pagador, beneficiarioFinal, mensagensInstrucao, gerarPdf, rateioCreditos, codigoCadastrarPIX, numeroContratoCobranca);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Boleto {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    codigoModalidade: ").append(toIndentedString(codigoModalidade)).append("\n");
    sb.append("    numeroContaCorrente: ").append(toIndentedString(numeroContaCorrente)).append("\n");
    sb.append("    codigoEspecieDocumento: ").append(toIndentedString(codigoEspecieDocumento)).append("\n");
    sb.append("    dataEmissao: ").append(toIndentedString(dataEmissao)).append("\n");
    sb.append("    nossoNumero: ").append(toIndentedString(nossoNumero)).append("\n");
    sb.append("    seuNumero: ").append(toIndentedString(seuNumero)).append("\n");
    sb.append("    identificacaoBoletoEmpresa: ").append(toIndentedString(identificacaoBoletoEmpresa)).append("\n");
    sb.append("    identificacaoEmissaoBoleto: ").append(toIndentedString(identificacaoEmissaoBoleto)).append("\n");
    sb.append("    identificacaoDistribuicaoBoleto: ").append(toIndentedString(identificacaoDistribuicaoBoleto)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    dataVencimento: ").append(toIndentedString(dataVencimento)).append("\n");
    sb.append("    dataLimitePagamento: ").append(toIndentedString(dataLimitePagamento)).append("\n");
    sb.append("    valorAbatimento: ").append(toIndentedString(valorAbatimento)).append("\n");
    sb.append("    tipoDesconto: ").append(toIndentedString(tipoDesconto)).append("\n");
    sb.append("    dataPrimeiroDesconto: ").append(toIndentedString(dataPrimeiroDesconto)).append("\n");
    sb.append("    valorPrimeiroDesconto: ").append(toIndentedString(valorPrimeiroDesconto)).append("\n");
    sb.append("    dataSegundoDesconto: ").append(toIndentedString(dataSegundoDesconto)).append("\n");
    sb.append("    valorSegundoDesconto: ").append(toIndentedString(valorSegundoDesconto)).append("\n");
    sb.append("    dataTerceiroDesconto: ").append(toIndentedString(dataTerceiroDesconto)).append("\n");
    sb.append("    valorTerceiroDesconto: ").append(toIndentedString(valorTerceiroDesconto)).append("\n");
    sb.append("    tipoMulta: ").append(toIndentedString(tipoMulta)).append("\n");
    sb.append("    dataMulta: ").append(toIndentedString(dataMulta)).append("\n");
    sb.append("    valorMulta: ").append(toIndentedString(valorMulta)).append("\n");
    sb.append("    tipoJurosMora: ").append(toIndentedString(tipoJurosMora)).append("\n");
    sb.append("    dataJurosMora: ").append(toIndentedString(dataJurosMora)).append("\n");
    sb.append("    valorJurosMora: ").append(toIndentedString(valorJurosMora)).append("\n");
    sb.append("    numeroParcela: ").append(toIndentedString(numeroParcela)).append("\n");
    sb.append("    aceite: ").append(toIndentedString(aceite)).append("\n");
    sb.append("    codigoNegativacao: ").append(toIndentedString(codigoNegativacao)).append("\n");
    sb.append("    numeroDiasNegativacao: ").append(toIndentedString(numeroDiasNegativacao)).append("\n");
    sb.append("    codigoProtesto: ").append(toIndentedString(codigoProtesto)).append("\n");
    sb.append("    numeroDiasProtesto: ").append(toIndentedString(numeroDiasProtesto)).append("\n");
    sb.append("    pagador: ").append(toIndentedString(pagador)).append("\n");
    sb.append("    beneficiarioFinal: ").append(toIndentedString(beneficiarioFinal)).append("\n");
    sb.append("    mensagensInstrucao: ").append(toIndentedString(mensagensInstrucao)).append("\n");
    sb.append("    gerarPdf: ").append(toIndentedString(gerarPdf)).append("\n");
    sb.append("    rateioCreditos: ").append(toIndentedString(rateioCreditos)).append("\n");
    sb.append("    codigoCadastrarPIX: ").append(toIndentedString(codigoCadastrarPIX)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

