/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FaixaNossoNumero
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class FaixaNossoNumero {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_NOME_CLIENTE = "nomeCliente";
  @SerializedName(SERIALIZED_NAME_NOME_CLIENTE)
  private String nomeCliente;

  public static final String SERIALIZED_NAME_NUMERO_INICIAL = "numeroInicial";
  @SerializedName(SERIALIZED_NAME_NUMERO_INICIAL)
  private Integer numeroInicial;

  public static final String SERIALIZED_NAME_NUMERO_FINAL = "numeroFinal";
  @SerializedName(SERIALIZED_NAME_NUMERO_FINAL)
  private Integer numeroFinal;

  public static final String SERIALIZED_NAME_QUANTIDADE = "quantidade";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE)
  private Integer quantidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  private Long numeroContratoCobranca;

  public static final String SERIALIZED_NAME_VALIDA_DIGITO_VERIFICADOR_NOSSO_NUMERO = "validaDigitoVerificadorNossoNumero";
  @SerializedName(SERIALIZED_NAME_VALIDA_DIGITO_VERIFICADOR_NOSSO_NUMERO)
  private Boolean validaDigitoVerificadorNossoNumero;


  public FaixaNossoNumero numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número do contrato
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "5224", required = true, value = "Número do contrato")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public FaixaNossoNumero nomeCliente(String nomeCliente) {
    
    this.nomeCliente = nomeCliente;
    return this;
  }

   /**
   * Nome do cliente
   * @return nomeCliente
  **/
  @ApiModelProperty(example = "JOSE PEREIRA", required = true, value = "Nome do cliente")

  public String getNomeCliente() {
    return nomeCliente;
  }


  public void setNomeCliente(String nomeCliente) {
    this.nomeCliente = nomeCliente;
  }


  public FaixaNossoNumero numeroInicial(Integer numeroInicial) {
    
    this.numeroInicial = numeroInicial;
    return this;
  }

   /**
   * Número do início da faixa
   * @return numeroInicial
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número do início da faixa")

  public Integer getNumeroInicial() {
    return numeroInicial;
  }


  public void setNumeroInicial(Integer numeroInicial) {
    this.numeroInicial = numeroInicial;
  }


  public FaixaNossoNumero numeroFinal(Integer numeroFinal) {
    
    this.numeroFinal = numeroFinal;
    return this;
  }

   /**
   * Número do final da faixa
   * @return numeroFinal
  **/
  @ApiModelProperty(example = "10", required = true, value = "Número do final da faixa")

  public Integer getNumeroFinal() {
    return numeroFinal;
  }


  public void setNumeroFinal(Integer numeroFinal) {
    this.numeroFinal = numeroFinal;
  }


  public FaixaNossoNumero quantidade(Integer quantidade) {
    
    this.quantidade = quantidade;
    return this;
  }

   /**
   * Quantidade
   * @return quantidade
  **/
  @ApiModelProperty(example = "10", required = true, value = "Quantidade")

  public Integer getQuantidade() {
    return quantidade;
  }


  public void setQuantidade(Integer quantidade) {
    this.quantidade = quantidade;
  }


  public FaixaNossoNumero numeroContratoCobranca(Long numeroContratoCobranca) {
    
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Indicar o id do contatroCobranca
   * @return numeroContratoCobranca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Indicar o id do contatroCobranca")

  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }


  public void setNumeroContratoCobranca(Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  public FaixaNossoNumero validaDigitoVerificadorNossoNumero(Boolean validaDigitoVerificadorNossoNumero) {
    
    this.validaDigitoVerificadorNossoNumero = validaDigitoVerificadorNossoNumero;
    return this;
  }

   /**
   * Indica que o contrato esta habilitado para validar o DV do NN.
   * @return validaDigitoVerificadorNossoNumero
  **/
  @ApiModelProperty(example = "true", required = true, value = "Indica que o contrato esta habilitado para validar o DV do NN.")

  public Boolean getValidaDigitoVerificadorNossoNumero() {
    return validaDigitoVerificadorNossoNumero;
  }


  public void setValidaDigitoVerificadorNossoNumero(Boolean validaDigitoVerificadorNossoNumero) {
    this.validaDigitoVerificadorNossoNumero = validaDigitoVerificadorNossoNumero;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaixaNossoNumero faixaNossoNumero = (FaixaNossoNumero) o;
    return Objects.equals(this.numeroCliente, faixaNossoNumero.numeroCliente) &&
        Objects.equals(this.nomeCliente, faixaNossoNumero.nomeCliente) &&
        Objects.equals(this.numeroInicial, faixaNossoNumero.numeroInicial) &&
        Objects.equals(this.numeroFinal, faixaNossoNumero.numeroFinal) &&
        Objects.equals(this.quantidade, faixaNossoNumero.quantidade) &&
        Objects.equals(this.numeroContratoCobranca, faixaNossoNumero.numeroContratoCobranca) &&
        Objects.equals(this.validaDigitoVerificadorNossoNumero, faixaNossoNumero.validaDigitoVerificadorNossoNumero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, nomeCliente, numeroInicial, numeroFinal, quantidade, numeroContratoCobranca, validaDigitoVerificadorNossoNumero);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaixaNossoNumero {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    nomeCliente: ").append(toIndentedString(nomeCliente)).append("\n");
    sb.append("    numeroInicial: ").append(toIndentedString(numeroInicial)).append("\n");
    sb.append("    numeroFinal: ").append(toIndentedString(numeroFinal)).append("\n");
    sb.append("    quantidade: ").append(toIndentedString(quantidade)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("    validaDigitoVerificadorNossoNumero: ").append(toIndentedString(validaDigitoVerificadorNossoNumero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

