/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2005Resultado
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class InlineResponse2005Resultado {
  public static final String SERIALIZED_NAME_QUANTIDADE_TOTAL_REGISTROS = "quantidadeTotalRegistros";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_TOTAL_REGISTROS)
  private Integer quantidadeTotalRegistros;

  public static final String SERIALIZED_NAME_QUANTIDADE_REGISTROS_ARQUIVO = "quantidadeRegistrosArquivo";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_REGISTROS_ARQUIVO)
  private Integer quantidadeRegistrosArquivo;

  public static final String SERIALIZED_NAME_QUANTIDADE_ARQUIVO = "quantidadeArquivo";
  @SerializedName(SERIALIZED_NAME_QUANTIDADE_ARQUIVO)
  private Integer quantidadeArquivo;

  public static final String SERIALIZED_NAME_ID_ARQUIVOS = "idArquivos";
  @SerializedName(SERIALIZED_NAME_ID_ARQUIVOS)
  private List<Integer> idArquivos = new ArrayList<>();


  public InlineResponse2005Resultado quantidadeTotalRegistros(Integer quantidadeTotalRegistros) {
    
    this.quantidadeTotalRegistros = quantidadeTotalRegistros;
    return this;
  }

   /**
   * Quantidade Total de Registos encontrados para a movimentação solicitada.
   * @return quantidadeTotalRegistros
  **/
  @ApiModelProperty(required = true, value = "Quantidade Total de Registos encontrados para a movimentação solicitada.")

  public Integer getQuantidadeTotalRegistros() {
    return quantidadeTotalRegistros;
  }


  public void setQuantidadeTotalRegistros(Integer quantidadeTotalRegistros) {
    this.quantidadeTotalRegistros = quantidadeTotalRegistros;
  }


  public InlineResponse2005Resultado quantidadeRegistrosArquivo(Integer quantidadeRegistrosArquivo) {
    
    this.quantidadeRegistrosArquivo = quantidadeRegistrosArquivo;
    return this;
  }

   /**
   * Quantidade Máxima de registos por arquivo.
   * @return quantidadeRegistrosArquivo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500000", value = "Quantidade Máxima de registos por arquivo.")

  public Integer getQuantidadeRegistrosArquivo() {
    return quantidadeRegistrosArquivo;
  }


  public void setQuantidadeRegistrosArquivo(Integer quantidadeRegistrosArquivo) {
    this.quantidadeRegistrosArquivo = quantidadeRegistrosArquivo;
  }


  public InlineResponse2005Resultado quantidadeArquivo(Integer quantidadeArquivo) {
    
    this.quantidadeArquivo = quantidadeArquivo;
    return this;
  }

   /**
   * Quantidade de arquivo(s) da movimentação retornada na consulta.
   * @return quantidadeArquivo
  **/
  @ApiModelProperty(example = "3", required = true, value = "Quantidade de arquivo(s) da movimentação retornada na consulta.")

  public Integer getQuantidadeArquivo() {
    return quantidadeArquivo;
  }


  public void setQuantidadeArquivo(Integer quantidadeArquivo) {
    this.quantidadeArquivo = quantidadeArquivo;
  }


  public InlineResponse2005Resultado idArquivos(List<Integer> idArquivos) {
    
    this.idArquivos = idArquivos;
    return this;
  }

  public InlineResponse2005Resultado addIdArquivosItem(Integer idArquivosItem) {
    this.idArquivos.add(idArquivosItem);
    return this;
  }

   /**
   * Get idArquivos
   * @return idArquivos
  **/
  @ApiModelProperty(example = "[30025254, 30025255, 30025256]", required = true, value = "")

  public List<Integer> getIdArquivos() {
    return idArquivos;
  }


  public void setIdArquivos(List<Integer> idArquivos) {
    this.idArquivos = idArquivos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005Resultado inlineResponse2005Resultado = (InlineResponse2005Resultado) o;
    return Objects.equals(this.quantidadeTotalRegistros, inlineResponse2005Resultado.quantidadeTotalRegistros) &&
        Objects.equals(this.quantidadeRegistrosArquivo, inlineResponse2005Resultado.quantidadeRegistrosArquivo) &&
        Objects.equals(this.quantidadeArquivo, inlineResponse2005Resultado.quantidadeArquivo) &&
        Objects.equals(this.idArquivos, inlineResponse2005Resultado.idArquivos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantidadeTotalRegistros, quantidadeRegistrosArquivo, quantidadeArquivo, idArquivos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005Resultado {\n");
    sb.append("    quantidadeTotalRegistros: ").append(toIndentedString(quantidadeTotalRegistros)).append("\n");
    sb.append("    quantidadeRegistrosArquivo: ").append(toIndentedString(quantidadeRegistrosArquivo)).append("\n");
    sb.append("    quantidadeArquivo: ").append(toIndentedString(quantidadeArquivo)).append("\n");
    sb.append("    idArquivos: ").append(toIndentedString(idArquivos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

