/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * InlineObject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class InlineObject {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_TIPO_MOVIMENTO = "tipoMovimento";
  @SerializedName(SERIALIZED_NAME_TIPO_MOVIMENTO)
  private Integer tipoMovimento;

  public static final String SERIALIZED_NAME_DATA_INICIAL = "dataInicial";
  @SerializedName(SERIALIZED_NAME_DATA_INICIAL)
  private LocalDate dataInicial;

  public static final String SERIALIZED_NAME_DATA_FINAL = "dataFinal";
  @SerializedName(SERIALIZED_NAME_DATA_FINAL)
  private LocalDate dataFinal;


  public InlineObject numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário no Sisbr.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "25546454", required = true, value = "Número que identifica o contrato do beneficiário no Sisbr.")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public InlineObject tipoMovimento(Integer tipoMovimento) {
    
    this.tipoMovimento = tipoMovimento;
    return this;
  }

   /**
   * Informe o tipo do movimento.   1 - Entrada   2 - Prorrogação   3 - A Vencer   4 - Vencido   5 - Liquidação   6 - Baixa   7 - Vinculado Operações Crédito
   * @return tipoMovimento
  **/
  @ApiModelProperty(example = "1", required = true, value = "Informe o tipo do movimento.   1 - Entrada   2 - Prorrogação   3 - A Vencer   4 - Vencido   5 - Liquidação   6 - Baixa   7 - Vinculado Operações Crédito")

  public Integer getTipoMovimento() {
    return tipoMovimento;
  }


  public void setTipoMovimento(Integer tipoMovimento) {
    this.tipoMovimento = tipoMovimento;
  }


  public InlineObject dataInicial(LocalDate dataInicial) {
    
    this.dataInicial = dataInicial;
    return this;
  }

   /**
   * Data inicial do movimento. Formato: yyyy-MM-dd 
   * @return dataInicial
  **/
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", required = true, value = "Data inicial do movimento. Formato: yyyy-MM-dd ")

  public LocalDate getDataInicial() {
    return dataInicial;
  }


  public void setDataInicial(LocalDate dataInicial) {
    this.dataInicial = dataInicial;
  }


  public InlineObject dataFinal(LocalDate dataFinal) {
    
    this.dataFinal = dataFinal;
    return this;
  }

   /**
   * Data final do movimento. Formato: yyyy-MM-dd 
   * @return dataFinal
  **/
  @ApiModelProperty(example = "Wed Sep 19 21:00:00 BRT 2018", required = true, value = "Data final do movimento. Formato: yyyy-MM-dd ")

  public LocalDate getDataFinal() {
    return dataFinal;
  }


  public void setDataFinal(LocalDate dataFinal) {
    this.dataFinal = dataFinal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.numeroCliente, inlineObject.numeroCliente) &&
        Objects.equals(this.tipoMovimento, inlineObject.tipoMovimento) &&
        Objects.equals(this.dataInicial, inlineObject.dataInicial) &&
        Objects.equals(this.dataFinal, inlineObject.dataFinal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, tipoMovimento, dataInicial, dataFinal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    tipoMovimento: ").append(toIndentedString(tipoMovimento)).append("\n");
    sb.append("    dataInicial: ").append(toIndentedString(dataInicial)).append("\n");
    sb.append("    dataFinal: ").append(toIndentedString(dataFinal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

