/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.InlineResponse20010RestHealthCheck;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20010
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class InlineResponse20010 {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_REST_HEALTH_CHECK = "RestHealthCheck";
  @SerializedName(SERIALIZED_NAME_REST_HEALTH_CHECK)
  private InlineResponse20010RestHealthCheck restHealthCheck;


  public InlineResponse20010 status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status geral da aplicação
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "UP", value = "Status geral da aplicação")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public InlineResponse20010 restHealthCheck(InlineResponse20010RestHealthCheck restHealthCheck) {
    
    this.restHealthCheck = restHealthCheck;
    return this;
  }

   /**
   * Get restHealthCheck
   * @return restHealthCheck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InlineResponse20010RestHealthCheck getRestHealthCheck() {
    return restHealthCheck;
  }


  public void setRestHealthCheck(InlineResponse20010RestHealthCheck restHealthCheck) {
    this.restHealthCheck = restHealthCheck;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return Objects.equals(this.status, inlineResponse20010.status) &&
        Objects.equals(this.restHealthCheck, inlineResponse20010.restHealthCheck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, restHealthCheck);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    restHealthCheck: ").append(toIndentedString(restHealthCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

