/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.SicoobMensagem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MensagensErro
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:07:18.842-03:00[America/Fortaleza]")
public class MensagensErro {
  public static final String SERIALIZED_NAME_MENSAGENS = "mensagens";
  @SerializedName(SERIALIZED_NAME_MENSAGENS)
  private List<SicoobMensagem> mensagens = new ArrayList<>();


  public MensagensErro mensagens(List<SicoobMensagem> mensagens) {
    
    this.mensagens = mensagens;
    return this;
  }

  public MensagensErro addMensagensItem(SicoobMensagem mensagensItem) {
    this.mensagens.add(mensagensItem);
    return this;
  }

   /**
   * Array com todas as mensagem de erro encontradas.
   * @return mensagens
  **/
  @ApiModelProperty(required = true, value = "Array com todas as mensagem de erro encontradas.")

  public List<SicoobMensagem> getMensagens() {
    return mensagens;
  }


  public void setMensagens(List<SicoobMensagem> mensagens) {
    this.mensagens = mensagens;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MensagensErro mensagensErro = (MensagensErro) o;
    return Objects.equals(this.mensagens, mensagensErro.mensagens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensagens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MensagensErro {\n");
    sb.append("    mensagens: ").append(toIndentedString(mensagens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

