/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Negativacao
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class Negativacao {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_CODIGO_MODALIDADE = "codigoModalidade";
  @SerializedName(SERIALIZED_NAME_CODIGO_MODALIDADE)
  private BigDecimal codigoModalidade;

  public static final String SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA = "numeroContratoCobranca";
  @SerializedName(SERIALIZED_NAME_NUMERO_CONTRATO_COBRANCA)
  private Long numeroContratoCobranca;


  public Negativacao numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário no Sisbr.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "25546454", required = true, value = "Número que identifica o contrato do beneficiário no Sisbr.")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public Negativacao codigoModalidade(BigDecimal codigoModalidade) {
    
    this.codigoModalidade = codigoModalidade;
    return this;
  }

   /**
   * Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 5 - CARNÊ DE PAGAMENTOS
   * @return codigoModalidade
  **/
  @ApiModelProperty(example = "1.0", required = true, value = "Número que identifica a modalidade do boleto. - 1 - SIMPLES COM REGISTRO - 5 - CARNÊ DE PAGAMENTOS")

  public BigDecimal getCodigoModalidade() {
    return codigoModalidade;
  }


  public void setCodigoModalidade(BigDecimal codigoModalidade) {
    this.codigoModalidade = codigoModalidade;
  }


  public Negativacao numeroContratoCobranca(Long numeroContratoCobranca) {
    
    this.numeroContratoCobranca = numeroContratoCobranca;
    return this;
  }

   /**
   * Indicar o id do contatroCobranca
   * @return numeroContratoCobranca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "Indicar o id do contatroCobranca")

  public Long getNumeroContratoCobranca() {
    return numeroContratoCobranca;
  }


  public void setNumeroContratoCobranca(Long numeroContratoCobranca) {
    this.numeroContratoCobranca = numeroContratoCobranca;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Negativacao negativacao = (Negativacao) o;
    return Objects.equals(this.numeroCliente, negativacao.numeroCliente) &&
        Objects.equals(this.codigoModalidade, negativacao.codigoModalidade) &&
        Objects.equals(this.numeroContratoCobranca, negativacao.numeroContratoCobranca);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, codigoModalidade, numeroContratoCobranca);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Negativacao {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    codigoModalidade: ").append(toIndentedString(codigoModalidade)).append("\n");
    sb.append("    numeroContratoCobranca: ").append(toIndentedString(numeroContratoCobranca)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

