/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Pagador
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class Pagador {
  public static final String SERIALIZED_NAME_NUMERO_CLIENTE = "numeroCliente";
  @SerializedName(SERIALIZED_NAME_NUMERO_CLIENTE)
  private Integer numeroCliente;

  public static final String SERIALIZED_NAME_NUMERO_CPF_CNPJ = "numeroCpfCnpj";
  @SerializedName(SERIALIZED_NAME_NUMERO_CPF_CNPJ)
  private String numeroCpfCnpj;

  public static final String SERIALIZED_NAME_NOME = "nome";
  @SerializedName(SERIALIZED_NAME_NOME)
  private String nome;

  public static final String SERIALIZED_NAME_ENDERECO = "endereco";
  @SerializedName(SERIALIZED_NAME_ENDERECO)
  private String endereco;

  public static final String SERIALIZED_NAME_BAIRRO = "bairro";
  @SerializedName(SERIALIZED_NAME_BAIRRO)
  private String bairro;

  public static final String SERIALIZED_NAME_CIDADE = "cidade";
  @SerializedName(SERIALIZED_NAME_CIDADE)
  private String cidade;

  public static final String SERIALIZED_NAME_CEP = "cep";
  @SerializedName(SERIALIZED_NAME_CEP)
  private String cep;

  public static final String SERIALIZED_NAME_UF = "uf";
  @SerializedName(SERIALIZED_NAME_UF)
  private String uf;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;


  public Pagador numeroCliente(Integer numeroCliente) {
    
    this.numeroCliente = numeroCliente;
    return this;
  }

   /**
   * Número que identifica o contrato do beneficiário.
   * @return numeroCliente
  **/
  @ApiModelProperty(example = "25546454", required = true, value = "Número que identifica o contrato do beneficiário.")

  public Integer getNumeroCliente() {
    return numeroCliente;
  }


  public void setNumeroCliente(Integer numeroCliente) {
    this.numeroCliente = numeroCliente;
  }


  public Pagador numeroCpfCnpj(String numeroCpfCnpj) {
    
    this.numeroCpfCnpj = numeroCpfCnpj;
    return this;
  }

   /**
   * CPF ou CNPJ do pagador do boleto de cobrança. &#x60;Tamanho máximo 14&#x60;
   * @return numeroCpfCnpj
  **/
  @ApiModelProperty(example = "98765432185", required = true, value = "CPF ou CNPJ do pagador do boleto de cobrança. `Tamanho máximo 14`")

  public String getNumeroCpfCnpj() {
    return numeroCpfCnpj;
  }


  public void setNumeroCpfCnpj(String numeroCpfCnpj) {
    this.numeroCpfCnpj = numeroCpfCnpj;
  }


  public Pagador nome(String nome) {
    
    this.nome = nome;
    return this;
  }

   /**
   * Nome completo do pagador do boleto de cobrança. &#x60;Tamanho máximo 50&#x60;
   * @return nome
  **/
  @ApiModelProperty(example = "Marcelo dos Santos", required = true, value = "Nome completo do pagador do boleto de cobrança. `Tamanho máximo 50`")

  public String getNome() {
    return nome;
  }


  public void setNome(String nome) {
    this.nome = nome;
  }


  public Pagador endereco(String endereco) {
    
    this.endereco = endereco;
    return this;
  }

   /**
   * Endereço do pagador do boleto de cobrança.
   * @return endereco
  **/
  @ApiModelProperty(example = "Rua 87 Quadra 1 Lote 1 casa 1", required = true, value = "Endereço do pagador do boleto de cobrança.")

  public String getEndereco() {
    return endereco;
  }


  public void setEndereco(String endereco) {
    this.endereco = endereco;
  }


  public Pagador bairro(String bairro) {
    
    this.bairro = bairro;
    return this;
  }

   /**
   * Bairro do pagador do boleto de cobrança.
   * @return bairro
  **/
  @ApiModelProperty(example = "Santa Rosa", required = true, value = "Bairro do pagador do boleto de cobrança.")

  public String getBairro() {
    return bairro;
  }


  public void setBairro(String bairro) {
    this.bairro = bairro;
  }


  public Pagador cidade(String cidade) {
    
    this.cidade = cidade;
    return this;
  }

   /**
   * Cidade do pagador do boleto de cobrança.
   * @return cidade
  **/
  @ApiModelProperty(example = "Luziânia", required = true, value = "Cidade do pagador do boleto de cobrança.")

  public String getCidade() {
    return cidade;
  }


  public void setCidade(String cidade) {
    this.cidade = cidade;
  }


  public Pagador cep(String cep) {
    
    this.cep = cep;
    return this;
  }

   /**
   * CEP do pagador do boleto de cobrança.
   * @return cep
  **/
  @ApiModelProperty(example = "72320000", required = true, value = "CEP do pagador do boleto de cobrança.")

  public String getCep() {
    return cep;
  }


  public void setCep(String cep) {
    this.cep = cep;
  }


  public Pagador uf(String uf) {
    
    this.uf = uf;
    return this;
  }

   /**
   * UF do pagador do boleto de cobrança.
   * @return uf
  **/
  @ApiModelProperty(example = "DF", required = true, value = "UF do pagador do boleto de cobrança.")

  public String getUf() {
    return uf;
  }


  public void setUf(String uf) {
    this.uf = uf;
  }


  public Pagador email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * E-mail do Pagador.
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pagador@dominio.com.br", value = "E-mail do Pagador.")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pagador pagador = (Pagador) o;
    return Objects.equals(this.numeroCliente, pagador.numeroCliente) &&
        Objects.equals(this.numeroCpfCnpj, pagador.numeroCpfCnpj) &&
        Objects.equals(this.nome, pagador.nome) &&
        Objects.equals(this.endereco, pagador.endereco) &&
        Objects.equals(this.bairro, pagador.bairro) &&
        Objects.equals(this.cidade, pagador.cidade) &&
        Objects.equals(this.cep, pagador.cep) &&
        Objects.equals(this.uf, pagador.uf) &&
        Objects.equals(this.email, pagador.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCliente, numeroCpfCnpj, nome, endereco, bairro, cidade, cep, uf, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pagador {\n");
    sb.append("    numeroCliente: ").append(toIndentedString(numeroCliente)).append("\n");
    sb.append("    numeroCpfCnpj: ").append(toIndentedString(numeroCpfCnpj)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    endereco: ").append(toIndentedString(endereco)).append("\n");
    sb.append("    bairro: ").append(toIndentedString(bairro)).append("\n");
    sb.append("    cidade: ").append(toIndentedString(cidade)).append("\n");
    sb.append("    cep: ").append(toIndentedString(cep)).append("\n");
    sb.append("    uf: ").append(toIndentedString(uf)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

