/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SicoobMensagem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class SicoobMensagem {
  public static final String SERIALIZED_NAME_MENSAGEM = "mensagem";
  @SerializedName(SERIALIZED_NAME_MENSAGEM)
  private String mensagem;

  public static final String SERIALIZED_NAME_CODIGO = "codigo";
  @SerializedName(SERIALIZED_NAME_CODIGO)
  private String codigo;


  public SicoobMensagem mensagem(String mensagem) {
    
    this.mensagem = mensagem;
    return this;
  }

   /**
   * Mensagem de retorno que pode ser informativa ou de erro
   * @return mensagem
  **/
  @ApiModelProperty(required = true, value = "Mensagem de retorno que pode ser informativa ou de erro")

  public String getMensagem() {
    return mensagem;
  }


  public void setMensagem(String mensagem) {
    this.mensagem = mensagem;
  }


  public SicoobMensagem codigo(String codigo) {
    
    this.codigo = codigo;
    return this;
  }

   /**
   * Código padrão de erro
   * @return codigo
  **/
  @ApiModelProperty(required = true, value = "Código padrão de erro")

  public String getCodigo() {
    return codigo;
  }


  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SicoobMensagem sicoobMensagem = (SicoobMensagem) o;
    return Objects.equals(this.mensagem, sicoobMensagem.mensagem) &&
        Objects.equals(this.codigo, sicoobMensagem.codigo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mensagem, codigo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SicoobMensagem {\n");
    sb.append("    mensagem: ").append(toIndentedString(mensagem)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

