/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import br.com.fidias.sicoob_cobranca.model.WebhookSolicitacoesWebhookSolicitacoes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WebhookSolicitacoes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:47:00.590-03:00[America/Fortaleza]")
public class WebhookSolicitacoes {
  public static final String SERIALIZED_NAME_PAGINA_ATUAL = "paginaAtual";
  @SerializedName(SERIALIZED_NAME_PAGINA_ATUAL)
  private Integer paginaAtual;

  public static final String SERIALIZED_NAME_TOTAL_PAGINAS = "totalPaginas";
  @SerializedName(SERIALIZED_NAME_TOTAL_PAGINAS)
  private Integer totalPaginas;

  public static final String SERIALIZED_NAME_TOTAL_REGISTROS = "totalRegistros";
  @SerializedName(SERIALIZED_NAME_TOTAL_REGISTROS)
  private Integer totalRegistros;

  public static final String SERIALIZED_NAME_WEBHOOK_SOLICITACOES = "webhookSolicitacoes";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_SOLICITACOES)
  private List<WebhookSolicitacoesWebhookSolicitacoes> webhookSolicitacoes = null;


  public WebhookSolicitacoes paginaAtual(Integer paginaAtual) {
    
    this.paginaAtual = paginaAtual;
    return this;
  }

   /**
   * Número da página atual
   * @return paginaAtual
  **/
  @ApiModelProperty(example = "1", required = true, value = "Número da página atual")

  public Integer getPaginaAtual() {
    return paginaAtual;
  }


  public void setPaginaAtual(Integer paginaAtual) {
    this.paginaAtual = paginaAtual;
  }


  public WebhookSolicitacoes totalPaginas(Integer totalPaginas) {
    
    this.totalPaginas = totalPaginas;
    return this;
  }

   /**
   * Total de páginas
   * @return totalPaginas
  **/
  @ApiModelProperty(example = "2", required = true, value = "Total de páginas")

  public Integer getTotalPaginas() {
    return totalPaginas;
  }


  public void setTotalPaginas(Integer totalPaginas) {
    this.totalPaginas = totalPaginas;
  }


  public WebhookSolicitacoes totalRegistros(Integer totalRegistros) {
    
    this.totalRegistros = totalRegistros;
    return this;
  }

   /**
   * Total de registros
   * @return totalRegistros
  **/
  @ApiModelProperty(example = "100", required = true, value = "Total de registros")

  public Integer getTotalRegistros() {
    return totalRegistros;
  }


  public void setTotalRegistros(Integer totalRegistros) {
    this.totalRegistros = totalRegistros;
  }


  public WebhookSolicitacoes webhookSolicitacoes(List<WebhookSolicitacoesWebhookSolicitacoes> webhookSolicitacoes) {
    
    this.webhookSolicitacoes = webhookSolicitacoes;
    return this;
  }

  public WebhookSolicitacoes addWebhookSolicitacoesItem(WebhookSolicitacoesWebhookSolicitacoes webhookSolicitacoesItem) {
    if (this.webhookSolicitacoes == null) {
      this.webhookSolicitacoes = new ArrayList<>();
    }
    this.webhookSolicitacoes.add(webhookSolicitacoesItem);
    return this;
  }

   /**
   * Get webhookSolicitacoes
   * @return webhookSolicitacoes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WebhookSolicitacoesWebhookSolicitacoes> getWebhookSolicitacoes() {
    return webhookSolicitacoes;
  }


  public void setWebhookSolicitacoes(List<WebhookSolicitacoesWebhookSolicitacoes> webhookSolicitacoes) {
    this.webhookSolicitacoes = webhookSolicitacoes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookSolicitacoes webhookSolicitacoes = (WebhookSolicitacoes) o;
    return Objects.equals(this.paginaAtual, webhookSolicitacoes.paginaAtual) &&
        Objects.equals(this.totalPaginas, webhookSolicitacoes.totalPaginas) &&
        Objects.equals(this.totalRegistros, webhookSolicitacoes.totalRegistros) &&
        Objects.equals(this.webhookSolicitacoes, webhookSolicitacoes.webhookSolicitacoes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginaAtual, totalPaginas, totalRegistros, webhookSolicitacoes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookSolicitacoes {\n");
    sb.append("    paginaAtual: ").append(toIndentedString(paginaAtual)).append("\n");
    sb.append("    totalPaginas: ").append(toIndentedString(totalPaginas)).append("\n");
    sb.append("    totalRegistros: ").append(toIndentedString(totalRegistros)).append("\n");
    sb.append("    webhookSolicitacoes: ").append(toIndentedString(webhookSolicitacoes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

