/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WebhookCadastro
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class WebhookCadastro {
  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_CODIGO_TIPO_MOVIMENTO = "codigoTipoMovimento";
  @SerializedName(SERIALIZED_NAME_CODIGO_TIPO_MOVIMENTO)
  private Integer codigoTipoMovimento;

  public static final String SERIALIZED_NAME_CODIGO_PERIODO_MOVIMENTO = "codigoPeriodoMovimento";
  @SerializedName(SERIALIZED_NAME_CODIGO_PERIODO_MOVIMENTO)
  private Integer codigoPeriodoMovimento;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;


  public WebhookCadastro url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL do webhook
   * @return url
  **/
  @ApiModelProperty(example = "https://webhook.com", required = true, value = "URL do webhook")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public WebhookCadastro codigoTipoMovimento(Integer codigoTipoMovimento) {
    
    this.codigoTipoMovimento = codigoTipoMovimento;
    return this;
  }

   /**
   * Código do tipo de movimento do webhook.   7 - Pagamento (Baixa operacional) 
   * @return codigoTipoMovimento
  **/
  @ApiModelProperty(example = "7", required = true, value = "Código do tipo de movimento do webhook.   7 - Pagamento (Baixa operacional) ")

  public Integer getCodigoTipoMovimento() {
    return codigoTipoMovimento;
  }


  public void setCodigoTipoMovimento(Integer codigoTipoMovimento) {
    this.codigoTipoMovimento = codigoTipoMovimento;
  }


  public WebhookCadastro codigoPeriodoMovimento(Integer codigoPeriodoMovimento) {
    
    this.codigoPeriodoMovimento = codigoPeriodoMovimento;
    return this;
  }

   /**
   * Código do período de movimento - 1 - Movimento atual (D0) 
   * @return codigoPeriodoMovimento
  **/
  @ApiModelProperty(example = "1", required = true, value = "Código do período de movimento - 1 - Movimento atual (D0) ")

  public Integer getCodigoPeriodoMovimento() {
    return codigoPeriodoMovimento;
  }


  public void setCodigoPeriodoMovimento(Integer codigoPeriodoMovimento) {
    this.codigoPeriodoMovimento = codigoPeriodoMovimento;
  }


  public WebhookCadastro email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * E-mail do associado
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "E-mail do associado")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookCadastro webhookCadastro = (WebhookCadastro) o;
    return Objects.equals(this.url, webhookCadastro.url) &&
        Objects.equals(this.codigoTipoMovimento, webhookCadastro.codigoTipoMovimento) &&
        Objects.equals(this.codigoPeriodoMovimento, webhookCadastro.codigoPeriodoMovimento) &&
        Objects.equals(this.email, webhookCadastro.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, codigoTipoMovimento, codigoPeriodoMovimento, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookCadastro {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    codigoTipoMovimento: ").append(toIndentedString(codigoTipoMovimento)).append("\n");
    sb.append("    codigoPeriodoMovimento: ").append(toIndentedString(codigoPeriodoMovimento)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

