/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Webhook
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-08T16:58:13.236-03:00[America/Fortaleza]")
public class Webhook {
  public static final String SERIALIZED_NAME_ID_WEBHOOK = "idWebhook";
  @SerializedName(SERIALIZED_NAME_ID_WEBHOOK)
  private Long idWebhook;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_CODIGO_TIPO_MOVIMENTO = "codigoTipoMovimento";
  @SerializedName(SERIALIZED_NAME_CODIGO_TIPO_MOVIMENTO)
  private Integer codigoTipoMovimento;

  public static final String SERIALIZED_NAME_DESCRICAO_TIPO_MOVIMENTO = "descricaoTipoMovimento";
  @SerializedName(SERIALIZED_NAME_DESCRICAO_TIPO_MOVIMENTO)
  private String descricaoTipoMovimento;

  public static final String SERIALIZED_NAME_CODIGO_PERIODO_MOVIMENTO = "codigoPeriodoMovimento";
  @SerializedName(SERIALIZED_NAME_CODIGO_PERIODO_MOVIMENTO)
  private Integer codigoPeriodoMovimento;

  public static final String SERIALIZED_NAME_DESCRICAO_PERIODO_MOVIMENTO = "descricaoPeriodoMovimento";
  @SerializedName(SERIALIZED_NAME_DESCRICAO_PERIODO_MOVIMENTO)
  private String descricaoPeriodoMovimento;

  public static final String SERIALIZED_NAME_CODIGO_SITUACAO = "codigoSituacao";
  @SerializedName(SERIALIZED_NAME_CODIGO_SITUACAO)
  private Integer codigoSituacao;

  public static final String SERIALIZED_NAME_DESCRICAO_SITUACAO = "descricaoSituacao";
  @SerializedName(SERIALIZED_NAME_DESCRICAO_SITUACAO)
  private String descricaoSituacao;

  public static final String SERIALIZED_NAME_DATA_HORA_CADASTRO = "dataHoraCadastro";
  @SerializedName(SERIALIZED_NAME_DATA_HORA_CADASTRO)
  private OffsetDateTime dataHoraCadastro;

  public static final String SERIALIZED_NAME_DATA_HORA_ULTIMA_ALTERACAO = "dataHoraUltimaAlteracao";
  @SerializedName(SERIALIZED_NAME_DATA_HORA_ULTIMA_ALTERACAO)
  private OffsetDateTime dataHoraUltimaAlteracao;

  public static final String SERIALIZED_NAME_DATA_HORA_INATIVACAO = "dataHoraInativacao";
  @SerializedName(SERIALIZED_NAME_DATA_HORA_INATIVACAO)
  private OffsetDateTime dataHoraInativacao;

  public static final String SERIALIZED_NAME_DESCRICAO_MOTIVO_INATIVACAO = "descricaoMotivoInativacao";
  @SerializedName(SERIALIZED_NAME_DESCRICAO_MOTIVO_INATIVACAO)
  private String descricaoMotivoInativacao;


  public Webhook idWebhook(Long idWebhook) {
    
    this.idWebhook = idWebhook;
    return this;
  }

   /**
   * Identificador único do webhook
   * @return idWebhook
  **/
  @ApiModelProperty(example = "4", required = true, value = "Identificador único do webhook")

  public Long getIdWebhook() {
    return idWebhook;
  }


  public void setIdWebhook(Long idWebhook) {
    this.idWebhook = idWebhook;
  }


  public Webhook url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL do webhook. A URL deve ser https.
   * @return url
  **/
  @ApiModelProperty(example = "https://webhook.com", required = true, value = "URL do webhook. A URL deve ser https.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public Webhook email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * E-mail associado ao webhook
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "webhook@email.com", value = "E-mail associado ao webhook")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public Webhook codigoTipoMovimento(Integer codigoTipoMovimento) {
    
    this.codigoTipoMovimento = codigoTipoMovimento;
    return this;
  }

   /**
   * Código do tipo de movimento do webhook.         7 - Pagamento (Baixa operacional) 
   * @return codigoTipoMovimento
  **/
  @ApiModelProperty(example = "7", required = true, value = "Código do tipo de movimento do webhook.         7 - Pagamento (Baixa operacional) ")

  public Integer getCodigoTipoMovimento() {
    return codigoTipoMovimento;
  }


  public void setCodigoTipoMovimento(Integer codigoTipoMovimento) {
    this.codigoTipoMovimento = codigoTipoMovimento;
  }


  public Webhook descricaoTipoMovimento(String descricaoTipoMovimento) {
    
    this.descricaoTipoMovimento = descricaoTipoMovimento;
    return this;
  }

   /**
   * Descrição do tipo de movimento
   * @return descricaoTipoMovimento
  **/
  @ApiModelProperty(example = "Pagamento (Baixa operacional)", required = true, value = "Descrição do tipo de movimento")

  public String getDescricaoTipoMovimento() {
    return descricaoTipoMovimento;
  }


  public void setDescricaoTipoMovimento(String descricaoTipoMovimento) {
    this.descricaoTipoMovimento = descricaoTipoMovimento;
  }


  public Webhook codigoPeriodoMovimento(Integer codigoPeriodoMovimento) {
    
    this.codigoPeriodoMovimento = codigoPeriodoMovimento;
    return this;
  }

   /**
   * Código do período de movimento - 1 - Movimento atual (D0) 
   * @return codigoPeriodoMovimento
  **/
  @ApiModelProperty(example = "1", required = true, value = "Código do período de movimento - 1 - Movimento atual (D0) ")

  public Integer getCodigoPeriodoMovimento() {
    return codigoPeriodoMovimento;
  }


  public void setCodigoPeriodoMovimento(Integer codigoPeriodoMovimento) {
    this.codigoPeriodoMovimento = codigoPeriodoMovimento;
  }


  public Webhook descricaoPeriodoMovimento(String descricaoPeriodoMovimento) {
    
    this.descricaoPeriodoMovimento = descricaoPeriodoMovimento;
    return this;
  }

   /**
   * Descrição do período de movimento
   * @return descricaoPeriodoMovimento
  **/
  @ApiModelProperty(example = "Movimento atual (D0)", required = true, value = "Descrição do período de movimento")

  public String getDescricaoPeriodoMovimento() {
    return descricaoPeriodoMovimento;
  }


  public void setDescricaoPeriodoMovimento(String descricaoPeriodoMovimento) {
    this.descricaoPeriodoMovimento = descricaoPeriodoMovimento;
  }


  public Webhook codigoSituacao(Integer codigoSituacao) {
    
    this.codigoSituacao = codigoSituacao;
    return this;
  }

   /**
   * Código da situação do webhook - 1 - Aguardando validação - 2 - Validado com sucesso - 3 - Inativo 
   * @return codigoSituacao
  **/
  @ApiModelProperty(example = "3", required = true, value = "Código da situação do webhook - 1 - Aguardando validação - 2 - Validado com sucesso - 3 - Inativo ")

  public Integer getCodigoSituacao() {
    return codigoSituacao;
  }


  public void setCodigoSituacao(Integer codigoSituacao) {
    this.codigoSituacao = codigoSituacao;
  }


  public Webhook descricaoSituacao(String descricaoSituacao) {
    
    this.descricaoSituacao = descricaoSituacao;
    return this;
  }

   /**
   * Descrição da situação
   * @return descricaoSituacao
  **/
  @ApiModelProperty(example = "Validado com sucesso", required = true, value = "Descrição da situação")

  public String getDescricaoSituacao() {
    return descricaoSituacao;
  }


  public void setDescricaoSituacao(String descricaoSituacao) {
    this.descricaoSituacao = descricaoSituacao;
  }


  public Webhook dataHoraCadastro(OffsetDateTime dataHoraCadastro) {
    
    this.dataHoraCadastro = dataHoraCadastro;
    return this;
  }

   /**
   * Data e hora de cadastro Formato: yyyy-MM-ddTHH:mm:ss.SSSZ
   * @return dataHoraCadastro
  **/
  @ApiModelProperty(example = "2024-09-03T00:27:18.483Z", required = true, value = "Data e hora de cadastro Formato: yyyy-MM-ddTHH:mm:ss.SSSZ")

  public OffsetDateTime getDataHoraCadastro() {
    return dataHoraCadastro;
  }


  public void setDataHoraCadastro(OffsetDateTime dataHoraCadastro) {
    this.dataHoraCadastro = dataHoraCadastro;
  }


  public Webhook dataHoraUltimaAlteracao(OffsetDateTime dataHoraUltimaAlteracao) {
    
    this.dataHoraUltimaAlteracao = dataHoraUltimaAlteracao;
    return this;
  }

   /**
   * Data e hora da última alteração Formato: yyyy-MM-ddTHH:mm:ss.SSSZ
   * @return dataHoraUltimaAlteracao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-09-06T12:24:11.296Z", value = "Data e hora da última alteração Formato: yyyy-MM-ddTHH:mm:ss.SSSZ")

  public OffsetDateTime getDataHoraUltimaAlteracao() {
    return dataHoraUltimaAlteracao;
  }


  public void setDataHoraUltimaAlteracao(OffsetDateTime dataHoraUltimaAlteracao) {
    this.dataHoraUltimaAlteracao = dataHoraUltimaAlteracao;
  }


  public Webhook dataHoraInativacao(OffsetDateTime dataHoraInativacao) {
    
    this.dataHoraInativacao = dataHoraInativacao;
    return this;
  }

   /**
   * Data e hora de inativação Formato: yyyy-MM-ddTHH:mm:ss.SSSZ
   * @return dataHoraInativacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-09-05T18:50:55.099Z", value = "Data e hora de inativação Formato: yyyy-MM-ddTHH:mm:ss.SSSZ")

  public OffsetDateTime getDataHoraInativacao() {
    return dataHoraInativacao;
  }


  public void setDataHoraInativacao(OffsetDateTime dataHoraInativacao) {
    this.dataHoraInativacao = dataHoraInativacao;
  }


  public Webhook descricaoMotivoInativacao(String descricaoMotivoInativacao) {
    
    this.descricaoMotivoInativacao = descricaoMotivoInativacao;
    return this;
  }

   /**
   * Descrição do motivo de inativação
   * @return descricaoMotivoInativacao
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Erro ao enviar notificação", value = "Descrição do motivo de inativação")

  public String getDescricaoMotivoInativacao() {
    return descricaoMotivoInativacao;
  }


  public void setDescricaoMotivoInativacao(String descricaoMotivoInativacao) {
    this.descricaoMotivoInativacao = descricaoMotivoInativacao;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhook webhook = (Webhook) o;
    return Objects.equals(this.idWebhook, webhook.idWebhook) &&
        Objects.equals(this.url, webhook.url) &&
        Objects.equals(this.email, webhook.email) &&
        Objects.equals(this.codigoTipoMovimento, webhook.codigoTipoMovimento) &&
        Objects.equals(this.descricaoTipoMovimento, webhook.descricaoTipoMovimento) &&
        Objects.equals(this.codigoPeriodoMovimento, webhook.codigoPeriodoMovimento) &&
        Objects.equals(this.descricaoPeriodoMovimento, webhook.descricaoPeriodoMovimento) &&
        Objects.equals(this.codigoSituacao, webhook.codigoSituacao) &&
        Objects.equals(this.descricaoSituacao, webhook.descricaoSituacao) &&
        Objects.equals(this.dataHoraCadastro, webhook.dataHoraCadastro) &&
        Objects.equals(this.dataHoraUltimaAlteracao, webhook.dataHoraUltimaAlteracao) &&
        Objects.equals(this.dataHoraInativacao, webhook.dataHoraInativacao) &&
        Objects.equals(this.descricaoMotivoInativacao, webhook.descricaoMotivoInativacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idWebhook, url, email, codigoTipoMovimento, descricaoTipoMovimento, codigoPeriodoMovimento, descricaoPeriodoMovimento, codigoSituacao, descricaoSituacao, dataHoraCadastro, dataHoraUltimaAlteracao, dataHoraInativacao, descricaoMotivoInativacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhook {\n");
    sb.append("    idWebhook: ").append(toIndentedString(idWebhook)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    codigoTipoMovimento: ").append(toIndentedString(codigoTipoMovimento)).append("\n");
    sb.append("    descricaoTipoMovimento: ").append(toIndentedString(descricaoTipoMovimento)).append("\n");
    sb.append("    codigoPeriodoMovimento: ").append(toIndentedString(codigoPeriodoMovimento)).append("\n");
    sb.append("    descricaoPeriodoMovimento: ").append(toIndentedString(descricaoPeriodoMovimento)).append("\n");
    sb.append("    codigoSituacao: ").append(toIndentedString(codigoSituacao)).append("\n");
    sb.append("    descricaoSituacao: ").append(toIndentedString(descricaoSituacao)).append("\n");
    sb.append("    dataHoraCadastro: ").append(toIndentedString(dataHoraCadastro)).append("\n");
    sb.append("    dataHoraUltimaAlteracao: ").append(toIndentedString(dataHoraUltimaAlteracao)).append("\n");
    sb.append("    dataHoraInativacao: ").append(toIndentedString(dataHoraInativacao)).append("\n");
    sb.append("    descricaoMotivoInativacao: ").append(toIndentedString(descricaoMotivoInativacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

