/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.api;

import br.com.fidias.sicoob_cobranca.ApiCallback;
import br.com.fidias.sicoob_cobranca.ApiClient;
import br.com.fidias.sicoob_cobranca.ApiException;
import br.com.fidias.sicoob_cobranca.ApiResponse;
import br.com.fidias.sicoob_cobranca.Configuration;
import br.com.fidias.sicoob_cobranca.Pair;
import br.com.fidias.sicoob_cobranca.ProgressRequestBody;
import br.com.fidias.sicoob_cobranca.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import br.com.fidias.sicoob_cobranca.model.MensagensErro;
import br.com.fidias.sicoob_cobranca.model.Pagador;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PagadorApi {
    private ApiClient localVarApiClient;

    public PagadorApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PagadorApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for pagadoresPut
     * @param pagador Informações do pagador. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Solicitação recebida com sucesso. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Possíveis erros de negócio. </td><td>  -  </td></tr>
        <tr><td> 406 </td><td> Possíveis erros de inconsistência nos dados passados. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro interno </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagadoresPutCall(Pagador pagador, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = pagador;

        // create path and map variables
        String localVarPath = "/pagadores";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pagadoresPutValidateBeforeCall(Pagador pagador, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'pagador' is set
        if (pagador == null) {
            throw new ApiException("Missing the required parameter 'pagador' when calling pagadoresPut(Async)");
        }
        

        okhttp3.Call localVarCall = pagadoresPutCall(pagador, _callback);
        return localVarCall;

    }

    /**
     * Alterar informações do cadastro do pagador.
     * Serviço para alterar informações do cadastro do pagador.
     * @param pagador Informações do pagador. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Solicitação recebida com sucesso. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Possíveis erros de negócio. </td><td>  -  </td></tr>
        <tr><td> 406 </td><td> Possíveis erros de inconsistência nos dados passados. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro interno </td><td>  -  </td></tr>
     </table>
     */
    public void pagadoresPut(Pagador pagador) throws ApiException {
        pagadoresPutWithHttpInfo(pagador);
    }

    /**
     * Alterar informações do cadastro do pagador.
     * Serviço para alterar informações do cadastro do pagador.
     * @param pagador Informações do pagador. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Solicitação recebida com sucesso. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Possíveis erros de negócio. </td><td>  -  </td></tr>
        <tr><td> 406 </td><td> Possíveis erros de inconsistência nos dados passados. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro interno </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> pagadoresPutWithHttpInfo(Pagador pagador) throws ApiException {
        okhttp3.Call localVarCall = pagadoresPutValidateBeforeCall(pagador, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Alterar informações do cadastro do pagador. (asynchronously)
     * Serviço para alterar informações do cadastro do pagador.
     * @param pagador Informações do pagador. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Solicitação recebida com sucesso. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Possíveis erros de negócio. </td><td>  -  </td></tr>
        <tr><td> 406 </td><td> Possíveis erros de inconsistência nos dados passados. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erro interno </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pagadoresPutAsync(Pagador pagador, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = pagadoresPutValidateBeforeCall(pagador, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
