/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import br.com.fidias.sicoob_cobranca.model.RateioCredito;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BoletoAlteracaoRateioCredito
 */
public class BoletoAlteracaoRateioCreditoTest {
    private final BoletoAlteracaoRateioCredito model = new BoletoAlteracaoRateioCredito();

    /**
     * Model tests for BoletoAlteracaoRateioCredito
     */
    @Test
    public void testBoletoAlteracaoRateioCredito() {
        // TODO: test BoletoAlteracaoRateioCredito
    }

    /**
     * Test the property 'tipoOperacao'
     */
    @Test
    public void tipoOperacaoTest() {
        // TODO: test tipoOperacao
    }

    /**
     * Test the property 'rateioCreditos'
     */
    @Test
    public void rateioCreditosTest() {
        // TODO: test rateioCreditos
    }

}
