/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoAbatimento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoDesconto;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoEspecieDocumento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoJurosMora;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoMulta;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoPix;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoProrrogacaoLimitePagamento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoProrrogacaoVencimento;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoRateioCredito;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoSeuNumero;
import br.com.fidias.sicoob_cobranca.model.BoletoAlteracaoValorNominal;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BoletoAlteracao
 */
public class BoletoAlteracaoTest {
    private final BoletoAlteracao model = new BoletoAlteracao();

    /**
     * Model tests for BoletoAlteracao
     */
    @Test
    public void testBoletoAlteracao() {
        // TODO: test BoletoAlteracao
    }

    /**
     * Test the property 'numeroCliente'
     */
    @Test
    public void numeroClienteTest() {
        // TODO: test numeroCliente
    }

    /**
     * Test the property 'codigoModalidade'
     */
    @Test
    public void codigoModalidadeTest() {
        // TODO: test codigoModalidade
    }

    /**
     * Test the property 'numeroContratoCobranca'
     */
    @Test
    public void numeroContratoCobrancaTest() {
        // TODO: test numeroContratoCobranca
    }

    /**
     * Test the property 'especieDocumento'
     */
    @Test
    public void especieDocumentoTest() {
        // TODO: test especieDocumento
    }

    /**
     * Test the property 'seuNumero'
     */
    @Test
    public void seuNumeroTest() {
        // TODO: test seuNumero
    }

    /**
     * Test the property 'desconto'
     */
    @Test
    public void descontoTest() {
        // TODO: test desconto
    }

    /**
     * Test the property 'abatimento'
     */
    @Test
    public void abatimentoTest() {
        // TODO: test abatimento
    }

    /**
     * Test the property 'multa'
     */
    @Test
    public void multaTest() {
        // TODO: test multa
    }

    /**
     * Test the property 'jurosMora'
     */
    @Test
    public void jurosMoraTest() {
        // TODO: test jurosMora
    }

    /**
     * Test the property 'rateioCredito'
     */
    @Test
    public void rateioCreditoTest() {
        // TODO: test rateioCredito
    }

    /**
     * Test the property 'pix'
     */
    @Test
    public void pixTest() {
        // TODO: test pix
    }

    /**
     * Test the property 'prorrogacaoVencimento'
     */
    @Test
    public void prorrogacaoVencimentoTest() {
        // TODO: test prorrogacaoVencimento
    }

    /**
     * Test the property 'prorrogacaoLimitePagamento'
     */
    @Test
    public void prorrogacaoLimitePagamentoTest() {
        // TODO: test prorrogacaoLimitePagamento
    }

    /**
     * Test the property 'valorNominal'
     */
    @Test
    public void valorNominalTest() {
        // TODO: test valorNominal
    }

}
