/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import br.com.fidias.sicoob_cobranca.model.InlineResponse200ResultadoBeneficiarioFinal;
import br.com.fidias.sicoob_cobranca.model.InlineResponse200ResultadoPagador;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse2003Resultado
 */
public class InlineResponse2003ResultadoTest {
    private final InlineResponse2003Resultado model = new InlineResponse2003Resultado();

    /**
     * Model tests for InlineResponse2003Resultado
     */
    @Test
    public void testInlineResponse2003Resultado() {
        // TODO: test InlineResponse2003Resultado
    }

    /**
     * Test the property 'numeroCliente'
     */
    @Test
    public void numeroClienteTest() {
        // TODO: test numeroCliente
    }

    /**
     * Test the property 'codigoModalidade'
     */
    @Test
    public void codigoModalidadeTest() {
        // TODO: test codigoModalidade
    }

    /**
     * Test the property 'codigoEspecieDocumento'
     */
    @Test
    public void codigoEspecieDocumentoTest() {
        // TODO: test codigoEspecieDocumento
    }

    /**
     * Test the property 'dataEmissao'
     */
    @Test
    public void dataEmissaoTest() {
        // TODO: test dataEmissao
    }

    /**
     * Test the property 'nossoNumero'
     */
    @Test
    public void nossoNumeroTest() {
        // TODO: test nossoNumero
    }

    /**
     * Test the property 'seuNumero'
     */
    @Test
    public void seuNumeroTest() {
        // TODO: test seuNumero
    }

    /**
     * Test the property 'codigoBarras'
     */
    @Test
    public void codigoBarrasTest() {
        // TODO: test codigoBarras
    }

    /**
     * Test the property 'linhaDigitavel'
     */
    @Test
    public void linhaDigitavelTest() {
        // TODO: test linhaDigitavel
    }

    /**
     * Test the property 'valor'
     */
    @Test
    public void valorTest() {
        // TODO: test valor
    }

    /**
     * Test the property 'dataVencimento'
     */
    @Test
    public void dataVencimentoTest() {
        // TODO: test dataVencimento
    }

    /**
     * Test the property 'valorAbatimento'
     */
    @Test
    public void valorAbatimentoTest() {
        // TODO: test valorAbatimento
    }

    /**
     * Test the property 'numeroParcela'
     */
    @Test
    public void numeroParcelaTest() {
        // TODO: test numeroParcela
    }

    /**
     * Test the property 'aceite'
     */
    @Test
    public void aceiteTest() {
        // TODO: test aceite
    }

    /**
     * Test the property 'tipoMulta'
     */
    @Test
    public void tipoMultaTest() {
        // TODO: test tipoMulta
    }

    /**
     * Test the property 'valorMulta'
     */
    @Test
    public void valorMultaTest() {
        // TODO: test valorMulta
    }

    /**
     * Test the property 'tipoJurosMora'
     */
    @Test
    public void tipoJurosMoraTest() {
        // TODO: test tipoJurosMora
    }

    /**
     * Test the property 'valorJurosMora'
     */
    @Test
    public void valorJurosMoraTest() {
        // TODO: test valorJurosMora
    }

    /**
     * Test the property 'pagador'
     */
    @Test
    public void pagadorTest() {
        // TODO: test pagador
    }

    /**
     * Test the property 'beneficiarioFinal'
     */
    @Test
    public void beneficiarioFinalTest() {
        // TODO: test beneficiarioFinal
    }

    /**
     * Test the property 'mensagensInstrucao'
     */
    @Test
    public void mensagensInstrucaoTest() {
        // TODO: test mensagensInstrucao
    }

    /**
     * Test the property 'pdfBoleto'
     */
    @Test
    public void pdfBoletoTest() {
        // TODO: test pdfBoleto
    }

    /**
     * Test the property 'qrCode'
     */
    @Test
    public void qrCodeTest() {
        // TODO: test qrCode
    }

    /**
     * Test the property 'numeroContratoCobranca'
     */
    @Test
    public void numeroContratoCobrancaTest() {
        // TODO: test numeroContratoCobranca
    }

    /**
     * Test the property 'tipoDesconto'
     */
    @Test
    public void tipoDescontoTest() {
        // TODO: test tipoDesconto
    }

}
