/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse200ResultadoPagador
 */
public class InlineResponse200ResultadoPagadorTest {
    private final InlineResponse200ResultadoPagador model = new InlineResponse200ResultadoPagador();

    /**
     * Model tests for InlineResponse200ResultadoPagador
     */
    @Test
    public void testInlineResponse200ResultadoPagador() {
        // TODO: test InlineResponse200ResultadoPagador
    }

    /**
     * Test the property 'numeroCpfCnpj'
     */
    @Test
    public void numeroCpfCnpjTest() {
        // TODO: test numeroCpfCnpj
    }

    /**
     * Test the property 'nome'
     */
    @Test
    public void nomeTest() {
        // TODO: test nome
    }

    /**
     * Test the property 'endereco'
     */
    @Test
    public void enderecoTest() {
        // TODO: test endereco
    }

    /**
     * Test the property 'bairro'
     */
    @Test
    public void bairroTest() {
        // TODO: test bairro
    }

    /**
     * Test the property 'cidade'
     */
    @Test
    public void cidadeTest() {
        // TODO: test cidade
    }

    /**
     * Test the property 'cep'
     */
    @Test
    public void cepTest() {
        // TODO: test cep
    }

    /**
     * Test the property 'uf'
     */
    @Test
    public void ufTest() {
        // TODO: test uf
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
