/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RateioCredito
 */
public class RateioCreditoTest {
    private final RateioCredito model = new RateioCredito();

    /**
     * Model tests for RateioCredito
     */
    @Test
    public void testRateioCredito() {
        // TODO: test RateioCredito
    }

    /**
     * Test the property 'numeroBanco'
     */
    @Test
    public void numeroBancoTest() {
        // TODO: test numeroBanco
    }

    /**
     * Test the property 'numeroAgencia'
     */
    @Test
    public void numeroAgenciaTest() {
        // TODO: test numeroAgencia
    }

    /**
     * Test the property 'numeroContaCorrente'
     */
    @Test
    public void numeroContaCorrenteTest() {
        // TODO: test numeroContaCorrente
    }

    /**
     * Test the property 'contaPrincipal'
     */
    @Test
    public void contaPrincipalTest() {
        // TODO: test contaPrincipal
    }

    /**
     * Test the property 'codigoTipoValorRateio'
     */
    @Test
    public void codigoTipoValorRateioTest() {
        // TODO: test codigoTipoValorRateio
    }

    /**
     * Test the property 'valorRateio'
     */
    @Test
    public void valorRateioTest() {
        // TODO: test valorRateio
    }

    /**
     * Test the property 'codigoTipoCalculoRateio'
     */
    @Test
    public void codigoTipoCalculoRateioTest() {
        // TODO: test codigoTipoCalculoRateio
    }

    /**
     * Test the property 'numeroCpfCnpjTitular'
     */
    @Test
    public void numeroCpfCnpjTitularTest() {
        // TODO: test numeroCpfCnpjTitular
    }

    /**
     * Test the property 'nomeTitular'
     */
    @Test
    public void nomeTitularTest() {
        // TODO: test nomeTitular
    }

    /**
     * Test the property 'codigoFinalidadeTed'
     */
    @Test
    public void codigoFinalidadeTedTest() {
        // TODO: test codigoFinalidadeTed
    }

    /**
     * Test the property 'codigoTipoContaDestinoTed'
     */
    @Test
    public void codigoTipoContaDestinoTedTest() {
        // TODO: test codigoTipoContaDestinoTed
    }

    /**
     * Test the property 'quantidadeDiasFloat'
     */
    @Test
    public void quantidadeDiasFloatTest() {
        // TODO: test quantidadeDiasFloat
    }

    /**
     * Test the property 'dataFloatCredito'
     */
    @Test
    public void dataFloatCreditoTest() {
        // TODO: test dataFloatCredito
    }

}
