/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Webhook
 */
public class WebhookTest {
    private final Webhook model = new Webhook();

    /**
     * Model tests for Webhook
     */
    @Test
    public void testWebhook() {
        // TODO: test Webhook
    }

    /**
     * Test the property 'idWebhook'
     */
    @Test
    public void idWebhookTest() {
        // TODO: test idWebhook
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'codigoTipoMovimento'
     */
    @Test
    public void codigoTipoMovimentoTest() {
        // TODO: test codigoTipoMovimento
    }

    /**
     * Test the property 'descricaoTipoMovimento'
     */
    @Test
    public void descricaoTipoMovimentoTest() {
        // TODO: test descricaoTipoMovimento
    }

    /**
     * Test the property 'codigoPeriodoMovimento'
     */
    @Test
    public void codigoPeriodoMovimentoTest() {
        // TODO: test codigoPeriodoMovimento
    }

    /**
     * Test the property 'descricaoPeriodoMovimento'
     */
    @Test
    public void descricaoPeriodoMovimentoTest() {
        // TODO: test descricaoPeriodoMovimento
    }

    /**
     * Test the property 'codigoSituacao'
     */
    @Test
    public void codigoSituacaoTest() {
        // TODO: test codigoSituacao
    }

    /**
     * Test the property 'descricaoSituacao'
     */
    @Test
    public void descricaoSituacaoTest() {
        // TODO: test descricaoSituacao
    }

    /**
     * Test the property 'dataHoraCadastro'
     */
    @Test
    public void dataHoraCadastroTest() {
        // TODO: test dataHoraCadastro
    }

    /**
     * Test the property 'dataHoraUltimaAlteracao'
     */
    @Test
    public void dataHoraUltimaAlteracaoTest() {
        // TODO: test dataHoraUltimaAlteracao
    }

    /**
     * Test the property 'dataHoraInativacao'
     */
    @Test
    public void dataHoraInativacaoTest() {
        // TODO: test dataHoraInativacao
    }

    /**
     * Test the property 'descricaoMotivoInativacao'
     */
    @Test
    public void descricaoMotivoInativacaoTest() {
        // TODO: test descricaoMotivoInativacao
    }

}
