/*
 * Cobrança Bancária
 * <pre>[ Base URL: https://api.sicoob.com.br/cobranca-bancaria/v3 ]</pre> A Cobrança Bancária Sicoob é um conjunto de serviços oferecidos a seus associados para recebimento de valores referentes às vendas de produtos e serviços da sua empresa, por meio de boletos de cobrança, pagos em toda a rede bancária. Esta API disponibiliza funcionalidades que auxiliam na gestão da carteira registrada, tornando viável todo o processo de acompanhamento, desde a inclusão de novos boletos, alteração de informações relevantes, protesto/negativação de títulos vencidos e não pagos, até a liquidação ou baixa do título.
 *
 * The version of the OpenAPI document: 3.0.8.0
 * Contact: GrupoGesin1CobrancaBancaria@sicoob.com.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package br.com.fidias.sicoob_cobranca.model;

import br.com.fidias.sicoob_cobranca.model.WebhookSolicitacoesWebhookNotificacoes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WebhookSolicitacoesWebhookSolicitacoes
 */
public class WebhookSolicitacoesWebhookSolicitacoesTest {
    private final WebhookSolicitacoesWebhookSolicitacoes model = new WebhookSolicitacoesWebhookSolicitacoes();

    /**
     * Model tests for WebhookSolicitacoesWebhookSolicitacoes
     */
    @Test
    public void testWebhookSolicitacoesWebhookSolicitacoes() {
        // TODO: test WebhookSolicitacoesWebhookSolicitacoes
    }

    /**
     * Test the property 'codigoWebhookSituacao'
     */
    @Test
    public void codigoWebhookSituacaoTest() {
        // TODO: test codigoWebhookSituacao
    }

    /**
     * Test the property 'descricaoWebhookSituacao'
     */
    @Test
    public void descricaoWebhookSituacaoTest() {
        // TODO: test descricaoWebhookSituacao
    }

    /**
     * Test the property 'codigoSolicitacaoSituacao'
     */
    @Test
    public void codigoSolicitacaoSituacaoTest() {
        // TODO: test codigoSolicitacaoSituacao
    }

    /**
     * Test the property 'descricaoSolicitacaoSituacao'
     */
    @Test
    public void descricaoSolicitacaoSituacaoTest() {
        // TODO: test descricaoSolicitacaoSituacao
    }

    /**
     * Test the property 'codigoTipoMovimento'
     */
    @Test
    public void codigoTipoMovimentoTest() {
        // TODO: test codigoTipoMovimento
    }

    /**
     * Test the property 'descricaoTipoMovimento'
     */
    @Test
    public void descricaoTipoMovimentoTest() {
        // TODO: test descricaoTipoMovimento
    }

    /**
     * Test the property 'codigoPeriodoMovimento'
     */
    @Test
    public void codigoPeriodoMovimentoTest() {
        // TODO: test codigoPeriodoMovimento
    }

    /**
     * Test the property 'descricaoPeriodoMovimento'
     */
    @Test
    public void descricaoPeriodoMovimentoTest() {
        // TODO: test descricaoPeriodoMovimento
    }

    /**
     * Test the property 'descricaoErroProcessamento'
     */
    @Test
    public void descricaoErroProcessamentoTest() {
        // TODO: test descricaoErroProcessamento
    }

    /**
     * Test the property 'dataHoraCadastro'
     */
    @Test
    public void dataHoraCadastroTest() {
        // TODO: test dataHoraCadastro
    }

    /**
     * Test the property 'validacaoWebhook'
     */
    @Test
    public void validacaoWebhookTest() {
        // TODO: test validacaoWebhook
    }

    /**
     * Test the property 'nossoNumero'
     */
    @Test
    public void nossoNumeroTest() {
        // TODO: test nossoNumero
    }

    /**
     * Test the property 'codigoBarras'
     */
    @Test
    public void codigoBarrasTest() {
        // TODO: test codigoBarras
    }

    /**
     * Test the property 'webhookNotificacoes'
     */
    @Test
    public void webhookNotificacoesTest() {
        // TODO: test webhookNotificacoes
    }

}
